/* ── ai.js ── */

function v641LoadPrefs(){try{return JSON.parse(localStorage.getItem(V641_PREF_KEY)||"{}")||{}}catch(e){return{}}}
function v641SavePrefsFromDom(){const prefs={style:$("v641TravelStyle")?.value||"",mbti:$("v641Mbti")?.value||"",zodiac:$("v641Zodiac")?.value||""};try{localStorage.setItem(V641_PREF_KEY,JSON.stringify(prefs))}catch(e){}return prefs}
function v641PrefsText(){const p=v641LoadPrefs();const parts=[];if(p.style)parts.push("旅遊風格偏好："+p.style);if(p.mbti)parts.push("MBTI："+p.mbti);if(p.zodiac)parts.push("星座："+p.zodiac);return parts.length?parts.join("\n"):"未填寫，請以一般旅遊者需求判斷。"}
function v641PrefsHtml(){const p=v641LoadPrefs();const opts=(arr,val)=>arr.map(x=>`<option value="${esc(x)}" ${x===(val||"")?"selected":""}>${x||"不指定"}</option>`).join("");return`<div class="v641Prefs"><div class="v641PrefsTitle">偏好參考（非必填）</div><div class="v641PrefsGrid"><div><label>旅遊風格</label><select id="v641TravelStyle" onchange="v641SavePrefsFromDom()">${opts(V641_STYLES,p.style)}</select></div><div><label>MBTI</label><select id="v641Mbti" onchange="v641SavePrefsFromDom()">${opts(V641_MBTIS,p.mbti)}</select></div><div><label>星座</label><select id="v641Zodiac" onchange="v641SavePrefsFromDom()">${opts(V641_ZODIACS,p.zodiac)}</select></div></div></div>`}
function v641EnsureAiReviews(){if(!data.aiReviews||typeof data.aiReviews!=="object")data.aiReviews={};if(!Array.isArray(data.aiReviews.itinerary))data.aiReviews.itinerary=[];return data.aiReviews.itinerary}
function v641SaveItineraryReview(obj){const reviews=v641EnsureAiReviews();const review={id:uid(),createdAt:new Date().toISOString(),summary:String(obj.summary||""),items:Array.isArray(obj.items)?obj.items.map(x=>({day:String(x.day||""),level:String(x.level||"建議"),title:String(x.title||"AI 建議"),memo:String(x.memo||"")})).filter(x=>x.title||x.memo):[]};reviews.unshift(review);data.aiReviews.itinerary=reviews.slice(0,5);return review}
function v641DeleteReview(id){if(!data.aiReviews?.itinerary)return;data.aiReviews.itinerary=data.aiReviews.itinerary.filter(x=>x.id!==id);save()}
function v641ReviewHtml(){const reviews=(data.aiReviews?.itinerary||[]).slice(0,3);if(!reviews.length)return"";return`<div class="v641ReviewList">${reviews.map(r=>`<div class="v641ReviewCard"><div class="v641ReviewHead"><div><b>AI 健檢建議</b><span>${esc((r.createdAt||"").slice(0,10))}</span></div><button class="small" onclick="v641DeleteReview('${r.id}')">刪除</button></div>${r.summary?`<div class="box mint">${esc(r.summary)}</div>`:""}</div>`).join("")}</div>`}

/* ── v64 AI 系統 ── */
function v64SafeOpen(url){try{open(url,"_blank")}catch(e){toast("無法開啟新視窗，請確認瀏覽器設定")}}
function v64Copy(text){return navigator.clipboard?.writeText(text).then(()=>toast("已複製")).catch(()=>{const ta=document.createElement("textarea");ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand("copy");document.body.removeChild(ta);toast("已複製")})}
function v64TripContext(){return{dest:data.trip?.dest||"未設定",country:data.trip?.country||"未設定",city:data.trip?.city||"",currency:data.trip?.currency||"KRW",dates:`${data.trip?.start||""} ～ ${data.trip?.end||""}`,travelers:(data.trip?.travelers||[]).join("、")||"未設定",days:data.days.map(d=>`${d.key}（${d.title}｜${d.label}）`).join("\n"),hotels:data.hotels.map(h=>`${short(h.start)}~${short(h.end)} ${h.name}${h.addr?("，區域："+h.addr):""}`).join("\n")||"尚未設定住宿"}}
function v64BuildPrompt(type,spotId){const c=v64TripContext();if(type==="spots"){return`請依照以下旅行設定，幫我產出可匯入「貞選旅管家」的口袋景點 JSON。\n\n旅行設定：\n- 目的地：${c.dest}\n- 國家/區域：${c.country}\n- 城市/路線：${c.city||c.dest}\n- 日期：${c.dates}\n- 旅伴：${c.travelers}\n\n旅行日期：\n${c.days}\n\n住宿：\n${c.hotels}\n\n請注意：\n1. 請推薦景點、餐廳、咖啡廳、購物、雨天備案。\n2. 如果適合某一天，請填 day；不確定就留空。\n3. 請只輸出純 JSON，格式如下：\n\n{\n  "spots": [\n    {\n      "name": "景點名稱",\n      "type": "景點/餐廳/咖啡廳/購物/雨天備案/其他",\n      "day": "YYYY-MM-DD，可留空",\n      "addr": "地址或區域",\n      "memo": "注意事項、推薦理由"\n    }\n  ]\n}`}if(type==="itinerary"){return`旅行資料：\n- 目的地：${c.dest}\n- 國家 / 區域：${c.country}\n- 日期：${c.dates}\n- 旅伴：${c.travelers}\n\n使用者偏好：\n${v641PrefsText()}\n\n${data.days.map(d=>{const plans=sortedPlans(d.key);const hotel=data.hotels.find(h=>d.key>=h.start&&d.key<=h.end);return`${d.title}｜${d.label}（${hotel?hotel.name:"住宿未設定"}）\n${plans.length?plans.map(p=>`  ${p.start||"--:--"} ${p.name}（${p.type}）${p.note?"\n  注意："+p.note:""}`).join("\n"):"  這天尚無行程"}`}).join("\n\n")}\n\n請做行程健檢，找出可能的時間衝突或改善點，並給予建議。回傳格式：\n{\n  "summary": "整體建議",\n  "items": [\n    {"day": "YYYY-MM-DD", "level": "注意/建議/OK", "title": "標題", "memo": "說明"}\n  ]\n}`}return""}
function v64EnsureAiPromptModal(){let modal=$("v64AiPromptModal");if(!modal){modal=document.createElement("div");modal.id="v64AiPromptModal";modal.className="aiPromptModal";document.body.appendChild(modal)}return modal}
function v64ShowPrompt(type,spotId){const modal=v64EnsureAiPromptModal();const prompt=v64BuildPrompt(type,spotId);const title=type==="spots"?"AI 口袋景點提示詞":type==="itinerary"?"AI 行程健檢提示詞":"AI 提示詞";modal.innerHTML=`<div class="aiPromptBox"><div class="section"><h3>${esc(title)}</h3><button class="iconBtn" onclick="v64CloseAiPrompt()">×</button></div>${type==="itinerary"?v641PrefsHtml():""}<textarea id="v64AiPromptText">${esc(prompt)}</textarea><div class="btns"><button class="btn dark" onclick="v64CopyAiPrompt()">複製提示詞</button><button class="btn blue" onclick="v64OpenAiTarget()">開啟 Claude AI</button><button class="btn soft" onclick="v64CloseAiPrompt()">關閉</button></div></div>`;modal.classList.add("show");$("v64AiPromptText").value=prompt}
function v64CloseAiPrompt(){$("v64AiPromptModal")?.classList.remove("show")}
function v64CopyAiPrompt(){const el=$("v64AiPromptText");if(el)v64Copy(el.value)}
function v64OpenAiTarget(){v64SafeOpen("https://claude.ai/")}
function showAIPrompt(){v64ShowPrompt("spots")}
function copyAIPrompt(){v64CopyAiPrompt()}
function closeAIPrompt(){v64CloseAiPrompt()}

/* v64 匯入 AI 回傳 JSON */
function v64EnsureImportModal(){let modal=$("v64ImportModal");if(!modal){modal=document.createElement("div");modal.id="v64ImportModal";modal.className="aiPromptModal";document.body.appendChild(modal)}return modal}
function v64OpenImportModal(){const modal=v64EnsureImportModal();modal.innerHTML=`<div class="aiPromptBox"><div class="section"><h3>匯入 AI 行程建議</h3><button class="iconBtn" onclick="v64CloseImportModal()">×</button></div><div class="hint">把 AI 回傳的 JSON 貼入下方文字框，再按「匯入到行程」。系統會把符合格式的行程資料合併進來。</div><textarea id="v64ImportText" placeholder='{"plans":[...]}'></textarea><div class="btns"><button class="btn dark" onclick="v64ImportAiText()">匯入到行程</button><button class="btn soft" onclick="v64CloseImportModal()">取消</button></div></div>`;modal.classList.add("show")}
function v64CloseImportModal(){$("v64ImportModal")?.classList.remove("show")}
function v64ArrayFromImport(obj,key){if(Array.isArray(obj[key]))return obj[key];if(Array.isArray(obj))return obj;return[]}
function v64ImportAiText(){const raw=$("v64ImportText")?.value||"";try{const obj=JSON.parse(normalizeImportedJsonText(raw));const spots=v64ArrayFromImport(obj,"spots");const reviews=v64ArrayFromImport(obj,"items");if(spots.length){spots.forEach(s=>{if(!s.name)return;const safeDay=v23NormalizeSpotDate(String(s.day||""));data.spots.push({id:uid(),name:String(s.name||""),type:String(s.type||"景點"),day:safeDay,addr:String(s.addr||""),memo:String(s.memo||""),source:"AI匯入"})});save();toast(`已匯入 ${spots.length} 個景點`);v64CloseImportModal()}else if(reviews.length||obj.summary){const review=v641SaveItineraryReview(obj);save();toast("已儲存 AI 行程建議");v64CloseImportModal()}else{toast("找不到可匯入的景點或建議資料，請確認 JSON 格式")}}catch(e){toast("JSON 格式錯誤："+e.message)}}

/* v64 AI 吧列 HTML（v644 最終版） */
function v64AiBarHtml(target){if(target==="spots"){return`<div class="aiBarV2 noPrint"><div class="aiBarLabel">AI 助理</div><div class="aiBarBtns"><button class="aiBarBtn" onclick="v64ShowPrompt('spots')">📝 AI 景點提示詞</button><button class="aiBarBtn" onclick="v64OpenImportModal()">📥 匯入 AI 回傳</button></div></div>`}if(target==="planner"){return`<div class="aiBarV2 noPrint"><div class="aiBarLabel">AI 助理</div><div class="aiBarBtns"><button class="aiBarBtn" onclick="v64ShowPrompt('itinerary')">🩺 AI 行程健檢</button><button class="aiBarBtn" onclick="v653OpenItineraryShare()">📤 分享行程</button></div></div>`}return""}

/* v64 AfterRender（注入 AI bar 到 renderSpots/renderPlanner 後） */
function v64AfterRender(){try{const spotsView=$("spotsView");if(spotsView&&!spotsView.querySelector(".aiBarV2")){const section=spotsView.querySelector(".section");if(section)section.insertAdjacentHTML("afterend",v64AiBarHtml("spots"))}}catch(e){}try{const planView=$("plannerView");if(planView&&!planView.querySelector(".aiBarV2.planner-bar")){const first=planView.querySelector(".section");if(first){const bar=document.createElement("div");bar.innerHTML=v64AiBarHtml("planner").replace('class="aiBarV2','class="aiBarV2 planner-bar');first.insertAdjacentHTML("afterend",bar.innerHTML)}};v653InsertPlannerShareButton()}catch(e){}}

/* ── v653 最終版 renderHelp（直接整合所有 renderHelp wrapper，不再需要 wrapper 鏈） ── */
