/* ── data.js ── */

function saveHotel(){if(!$("hname").value)return toast("請輸入住宿名稱");let start=$("hstart").value,end=$("hend").value;if(!v23ValidateHotelDates(start,end))return;const item={name:$("hname").value,start,end,addr:$("haddr").value,note:$("hnote").value};let hotelId=editingHotelId,isNew=false;if(editingHotelId){Object.assign(data.hotels.find(x=>x.id==editingHotelId),item);editingHotelId=null}else{isNew=true;hotelId=uid();data.hotels.push({id:hotelId,...item})}v18SortHotels();if(!isNew&&hotelHasPlans(hotelId)){addHotelPlans(hotelId)}else{v16KeepHotelOpen=true;silentSave();render()}v16OpenTripDetail(2);if(isNew){v21PendingHotelId=hotelId;$("hotelOptionModal")?.classList.add("show")}else toast("已幫你存好住宿囉！")}
function saveFlights(){if(!validateFlightSegments())return;const alreadyHasPlans=flightHasPlans();data.flights.out=readFlightForm("out");data.flights.back=readFlightForm("back");v39FlightDirty=false;if(alreadyHasPlans)syncFlightPlans();silentSave();render();v16CollapseTripDetail(0);toast(alreadyHasPlans?"已存好航班，並更新行程囉！":"已幫你存好航班囉！")}

/* v39 航班狀態顯示 */
function savePlanForm(){if(!$("pname").value)return toast("請輸入行程名稱");if(!v23ValidatePlanForm())return;const safeType=normalizePlanType($("ptype").value);let item={day:$("pday").value,start:$("ps").value,end:$("pe").value,type:safeType,name:$("pname").value,address:$("paddress")?.value||"",source:"manual",mode:"foreign",foreign:0,twd:0,payer:"未定",payMethod:"未定",note:$("pnote").value,memo:$("pmemo").value,adjusted:false};let planId=editingPlanId,isNew=false;if(editingPlanId){const existing=data.plans.find(p=>p.id==editingPlanId);if(existing?.lockedName){item.name=existing.name;item.source=existing.source||v28NormalizeSourceFromLegacy(existing);item.sourceType=existing.sourceType;item.lockedName=true;if(existing.hotelId)item.hotelId=existing.hotelId;if(item.source==="flight"||item.source==="hotel")item.address=""}Object.assign(existing,item);existing.type=normalizePlanType(existing.type);if(typeof existing.address==="undefined")existing.address="";editingPlanId=null}else{isNew=true;planId=uid();data.plans.push({id:planId,...item})}if(v16PendingSpotId){const spot=data.spots.find(s=>s.id==v16PendingSpotId);const p=data.plans.find(x=>x.id==planId);if(spot&&p){spot.planId=planId;p.source="manual";p.sourceType="spot";p.lockedName=true;p.name=spot.name;p.type=normalizePlanType(p.type||spot.type||"景點");p.address=spot.addr||p.address||"";p.memo=p.memo||"由口袋景點帶入"}v16PendingSpotId=null}const savedPlan=data.plans.find(x=>x.id==planId);if(isNew&&savedPlan){savedPlan.type=normalizePlanType(savedPlan.type);if(typeof savedPlan.address==="undefined")savedPlan.address="";createBudgetFromPlanSnapshot(savedPlan)}setCurrentDay(item.day,{render:false});save();toast(isNew?"行程加好了，也幫你先記一筆花費！":"已幫你存好行程囉！")}
function saveSpot(){if(!$("sn")?.value)return toast("請輸入名稱");const item={name:$("sn").value,type:normalizePlanType($("st").value),day:$("sd").value,addr:$("sa").value,memo:$("sm").value,start:v645TimeValue($("sStart")?.value||""),end:v645TimeValue($("sEnd")?.value||"")};let id=editingSpotId,spot;if(id){spot=(data.spots||[]).find(x=>x.id===id);if(spot)Object.assign(spot,item);editingSpotId=null}else{id=uid();spot={id,...item,source:"手動"};data.spots.push(spot)}if($("sToPlan")?.value==="yes"){const day=item.day||(typeof currentDay!=="undefined"?currentDay:cur)||cur;const planId=uid();const p={id:planId,sourceType:"spot",lockedName:true,day,start:item.start||"10:00",end:item.end||"11:30",type:normalizePlanType(item.type),name:item.name,address:item.addr||"",mode:"foreign",foreign:0,twd:0,payer:"未定",payMethod:"未定",note:item.memo,memo:"由口袋景點帶入",adjusted:false};data.plans.push(p);createBudgetFromPlanSnapshot(p);if(spot)spot.planId=planId}save()}

/* ── 預算 CRUD ── */
function saveExpenseForm(){if(!$("ename").value)return toast("請輸入費用項目");const item={source:"額外費用",type:$("etype").value,name:$("ename").value,payer:$("epayer").value,payMethod:$("epm").value,day:$("eday").value,mode:"foreign",foreign:Number($("eforeign").value||0),twd:Number($("etwd").value||0),memo:$("ememo").value};if(editingExpenseId){Object.assign(data.expenses.find(e=>e.id==editingExpenseId),item);editingExpenseId=null}else data.expenses.push({id:uid(),...item});save();toast("已幫你記好這筆花費！")}
function savePhotoEditModal(){const id=window.activePhotoEditId;const p=(data.photos||[]).find(x=>x.id===id);if(!p)return;p.title=document.getElementById("modalPhotoTitle")?.value||"";p.memo=document.getElementById("modalPhotoMemo")?.value||"";closePhotoEditModal();save();toast("照片日記已更新")}

/* v646 照片方向判斷 */
function exportBackup(){let blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`travel-book-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function importBackup(file){if(!file)return;if(!confirm("匯入備份會覆蓋目前資料，確定繼續？"))return;let r=new FileReader();r.onload=e=>{try{data=JSON.parse(e.target.result);if(!data.days?.length)data.days=mkDays(data.trip.start,data.trip.end);v63PersistTripLocal();cur=data.days[0]?.key||data.trip.start;render();toast("已匯入備份")}catch(err){toast("備份檔格式錯誤")}};r.readAsText(file)}

/* normalizeImportedJsonText */
function sample(){data=v63CloneBase();data.meta.title="釜山小旅行手帳";data.meta.subtitle="把海風、咖啡廳、夜市小吃和想拍的街景慢慢收進行程裡，準備一趟剛剛好的釜山旅行。";data.trip={dest:"韓國釜山",country:"韓國",city:"釜山",currency:"KRW",start:"2026-06-04",end:"2026-06-10",rate:.023,travelerCount:2,travelers:["Jane","Allen"]};data.days=mkDays(data.trip.start,data.trip.end);data.flights.out={type:"direct",segments:[{no:"BX 範例去程",from:"TPE 桃園",to:"PUS 金海",dep:"2026-06-04T10:00",arr:"2026-06-04T13:20",fromTerminal:"未定",toTerminal:"未定"}],toAirport:"抵達後搭機場輕軌或計程車前往飯店。",fromAirport:""};data.flights.back={type:"direct",segments:[{no:"BX 範例回程",from:"PUS 金海",to:"TPE 桃園",dep:"2026-06-10T14:30",arr:"2026-06-10T16:10",fromTerminal:"未定",toTerminal:"未定"}],toAirport:"建議提早 3 小時出發。",fromAirport:""};data.hotels=[{id:uid(),name:"城市律動",start:"2026-06-05",end:"2026-06-07",addr:"釜山西面站附近",note:"近地鐵，晚上回飯店方便。"}];data.expenses=[{id:uid(),source:"住宿",type:"住宿",name:"6/5~6/7 城市律動",payer:"1",payMethod:"card",day:"",mode:"TWD",foreign:0,twd:18000,memo:"範例"}];data.spots=[["甘川洞文化村","景點","2026-06-05"],["海雲台","景點","2026-06-06"],["西面商圈","購物","2026-06-07"]].map(x=>({id:uid(),name:x[0],type:x[1],day:x[2],addr:"釜山",memo:"範例口袋景點",start:"",end:"",source:"手動"}));cur=data.days[0].key;currentDay=cur;v63PersistTripLocal();render();toast("已加入範例")}
function resetAll(){if(!confirm("確定清除全部資料？"))return;v63PersistTripLocal();data=v63CloneBase();cur=data.days[0]?.key||data.trip.start;currentDay=cur;render()}

/* ── 主題系統 ── */
function saveThemePrefs(prefs){localStorage.setItem(THEME_STORAGE_KEY,JSON.stringify(prefs))}
function saveBasic(){const basic=v643ReadTripBasicFromForm();if(basic.country!==data.trip.country){v18PendingCountry=basic.country;if($("country"))$("country").value=data.trip.country;$("countryResetModal")?.classList.add("show");return}const dateChanged=basic.start!==data.trip.start||basic.end!==data.trip.end;if(dateChanged&&data.days?.length){v643PendingBasic=basic;v19PendingDates={start:basic.start,end:basic.end};v643OpenDateAdjustModal();return}v643SaveBasicNoDateChange(basic)}

/* v643 日期範圍外提示（注入 renderTrip 末尾） */
function showSyncMini(text){const el=$("syncMini");if(!el)return;el.textContent=text||"已同步";el.classList.add("show");clearTimeout(window.__syncMiniTimer);window.__syncMiniTimer=setTimeout(()=>el.classList.remove("show"),1600)}
function updateAccountSyncLine(){const el=$("accountSyncLine");if(!el)return;const label=v649ReadOnly?"檢視模式":typeof v648SyncLabelFromState==="function"?v648SyncLabelFromState():(fbUser?"尚未同步":"尚未登入");const dotClass=v649ReadOnly?"syncing":typeof v648SyncDotClassFromState==="function"?v648SyncDotClassFromState():"";el.innerHTML=`<span class="dot ${dotClass}"></span>${esc(label)}`}
function v648SyncLabelFromState(){if(v649ReadOnly)return"檢視模式";const s=v632LastSyncState||{};if(s.kind==="on")return`已同步${s.at?new Date(s.at).toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit"})?"  "+new Date(s.at).toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit"}):"":""}`;if(s.kind==="warn"){const t=String(s.title||"");if(t.includes("等待"))return"等待同步";if(t.includes("排隊"))return"同步排隊中";if(t.includes("載入"))return"載入中";return"同步中"}if(s.kind==="off"){const t=String(s.title||"");if(t.includes("尚未登入"))return"尚未登入";if(t.includes("尚未同步"))return"尚未同步";if(t.includes("無資料"))return"雲端無資料";if(t.includes("未授權"))return"帳號未授權";return t||"同步失敗"}return fbUser?"尚未同步":"尚未登入"}
function v648SyncDotClassFromState(){if(v649ReadOnly)return"syncing";const s=v632LastSyncState||{};if(s.kind==="on")return"success";if(s.kind==="warn")return"syncing";if(s.kind==="off")return"error";return""}

/* v649 最終版 setSyncStatus（直接整合裝置鎖判斷） */
function setSyncStatus(kind,title,desc){let k=kind,t=title,d=desc;if(v649ReadOnly&&kind==="on"&&String(title||"").includes("同步")){k="warn";t="檢視模式";d=`這趟旅程由 ${v649LockOwnerText()} 編輯中`}v632LastSyncState={kind:k||"off",title:t||"",desc:d||"",at:Date.now()};const dotClass=k==="on"?"on":k==="warn"?"warn":"off";const shortTitle=String(t||"").replace("已同步雲端","同步好了").replace("已同步到雲端","同步好了");const html=`<span class="syncDot ${dotClass}"></span><b>${esc(shortTitle)}</b>${d?`<br>${esc(d)}`:""}`;const el=$("syncStatus");if(el)el.innerHTML=html;const mini=$("syncMini");if(mini){mini.textContent=`${shortTitle}${d?"｜"+d:""}`;mini.classList.add("show");setTimeout(()=>mini.classList.remove("show"),1800)}const line=$("accountSyncLine");if(line){const state=k==="on"?"success":k==="warn"?"syncing":k==="off"?"error":"";line.innerHTML=`<span class="dot ${state}"></span>${esc(shortTitle||"同步狀態")}`}}
function v632StatusBadge(){const s=v632LastSyncState||{};const kind=s.kind||"off";const label=kind==="on"?"雲端已同步":kind==="warn"?"雲端同步中":"雲端未確認";const time=s.at?new Date(s.at).toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit"}):"";return`<span class="syncCloudBadge ${kind}">${label}${time?`｜${time}`:""}</span>`}

/* ── Firebase/云端認證工具 ── */
function firebaseSignIn(){if(!fbAuth)return toast("Firebase 尚未初始化");const provider=new firebase.auth.GoogleAuthProvider();fbAuth.signInWithPopup(provider).catch(err=>{alert("登入失敗："+err.message)})}
function firebaseSignOut(){v649StopHeartbeat();if(v649LockUnsub){try{v649LockUnsub()}catch(e){}v649LockUnsub=null};if(fbAuth)fbAuth.signOut()}
function v632IsAllowed(){return!!(fbUser&&typeof v63IsAllowed==="function"&&v63IsAllowed(fbUser))}
function v632CanUseCloud(showToast=false){if(!fbUser){if(showToast)toast("請先登入 Google");return false}if(!v632IsAllowed()){if(showToast)toast("這個帳號還沒授權同步");return false}if(!fbDb){if(showToast)toast("Firebase 尚未初始化");return false}if(!currentTripId){if(showToast)toast("請先選擇旅程");return false}return true}
function v632CloudPathText(){if(!fbUser||!currentTripId)return"尚未選擇旅程";return`users/${fbUser.uid}/trips/${currentTripId}`}
function v632Now(){return Date.now()}
function v632LocalMetaKey(tripId=currentTripId){return`${getLocalTripKey(tripId)}__meta`}
function v632GetLocalMeta(tripId=currentTripId){try{return JSON.parse(localStorage.getItem(v632LocalMetaKey(tripId))||"{}")}catch(e){return{}}}
function v632SetLocalMeta(tripId=currentTripId,meta={}){if(!tripId)return;localStorage.setItem(v632LocalMetaKey(tripId),JSON.stringify({...v632GetLocalMeta(tripId),...meta}))}

/* cloudPayload（v649 版，含裝置鎖） */
function cloudPayload(){return{appVersion:APP_VERSION,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAtClient:v632Now(),ownerEmail:fbUser?.email||"",tripId:currentTripId||"",tripMeta:typeof v63TripMetaFromData==="function"?v63TripMetaFromData(currentTripId):{},data:JSON.parse(JSON.stringify(data)),deviceId:v649DeviceId,deviceName:v649DeviceName(),editingLock:v649LockPayload(),lockUpdatedAtClient:v649Now()}}

/* ── v649 裝置鎖核心（直接整合版） ── */
function v63PersistTripLocal(){if(currentTripId){localStorage.setItem(getLocalTripKey(currentTripId),JSON.stringify(data));v632SetLocalMeta(currentTripId,{updatedAtClient:v632Now(),tripId:currentTripId,title:data?.meta?.title||"",dest:data?.trip?.dest||""});try{localStorage.setItem("voyageMemoData",JSON.stringify(data))}catch(e){}}}
function save(){if(v649ReadOnly){toast("目前是檢視模式，請先接手編輯");setSyncStatus("warn","檢視模式","此裝置不會儲存變更，避免覆蓋雲端。");return}v63PersistTripLocal();if(typeof v63UpdateCurrentTripMeta==="function")v63UpdateCurrentTripMeta(false);render();scheduleCloudSave("save")}
function silentSave(){if(v649ReadOnly)return;v63PersistTripLocal();if(typeof v63UpdateCurrentTripMeta==="function")v63UpdateCurrentTripMeta(false);scheduleCloudSave("silentSave")}

/* ── 最終整合版 scheduleCloudSave（v647 排隊 + v649 裝置鎖） ── */
function scheduleCloudSave(reason="auto"){if(v649SelectingTrip)return;if(v649ReadOnly){setSyncStatus("warn","檢視模式","此裝置不會自動同步，避免覆蓋編輯裝置。");v649ApplyLockBanner();return}if(suppressCloudSave)return;if(!v632CanUseCloud(false)){setSyncStatus("warn","本機已儲存","登入後可手動同步到雲端。");return}v647LastSaveReason=reason;clearTimeout(cloudSaveTimer);clearTimeout(v647CloudSaveTimer);setSyncStatus("warn","等待同步","已先儲存在本機，稍後寫入雲端。");v647CloudSaveTimer=setTimeout(()=>saveToCloudNow({silent:true,reason}),1800)}

/* ── 最終整合版 saveToCloudNow（v647 排隊 + v649 裝置鎖 + canWrite 檢查） ── */
async function saveToCloudNow(options={}){if(v649ReadOnly&&!options.allowReadOnly){setSyncStatus("warn","檢視模式","請先接手編輯，才可以同步寫入。");toast("目前是檢視模式，請先接手編輯");return false}if(fbUser&&currentTripId){const canWrite=await v649EnsureCanWrite();if(!canWrite){setSyncStatus("warn","檢視模式",`這趟旅程由 ${v649LockOwnerText()} 編輯中`);return false}}if(!v632CanUseCloud(!options.silent))return false;if(v647CloudSaveInFlight){v647CloudSaveQueued=true;setSyncStatus("warn","同步排隊中","上一筆資料仍在寫入，完成後會再同步一次。");return false}v647CloudSaveInFlight=true;v647CloudSaveQueued=false;try{clearTimeout(cloudSaveTimer);clearTimeout(v647CloudSaveTimer);setSyncStatus("warn","同步中","正在寫入雲端資料。");const now=v632Now();lastCloudUpdatedAt=now;const payload=cloudPayload();payload.updatedAtClient=now;payload.updatedAt=firebase.firestore.FieldValue.serverTimestamp();payload.tripMeta={...(payload.tripMeta||{}),updatedAtClient:now};await tripDocRef().set(payload,{merge:true});cloudReady=true;v632SetLocalMeta(currentTripId,{updatedAtClient:now,cloudUpdatedAtClient:now,cloudPath:v632CloudPathText()});if(typeof v63UpdateCurrentTripMeta==="function"){await v63UpdateCurrentTripMeta(false);await v632SaveTripIndexCloud()}try{localStorage.setItem(`janeselect_cloud_backup_${currentTripId}`,JSON.stringify(data));localStorage.setItem("travel_book_v22_cloud_backup",JSON.stringify(data))}catch(e){}setSyncStatus("on","同步好了",`${new Date(now).toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit"})}`);if(!options.silent)toast("已同步到雲端");v649StartHeartbeat();v649ApplyLockBanner();v647CloudSaveInFlight=false;if(v647CloudSaveQueued){v647CloudSaveQueued=false;setTimeout(()=>saveToCloudNow({silent:true,reason:"queued"}),350)}return true}catch(err){v647CloudSaveInFlight=false;const msg=err?.message||String(err)||"請檢查 Firestore Rules 與網路。";setSyncStatus("off","同步失敗",msg);if(!options.silent)alert("同步失敗："+msg);return false}}

/* loadFromCloud（v649 wrap 版） */
async function loadFromCloud(options={}){const silent=!!options.silent;if(!v632CanUseCloud(!silent))return false;if(!silent&&!options.force&&!confirm("載入雲端資料會覆蓋目前此裝置上的同一趟旅程資料。確定載入嗎？"))return false;try{setSyncStatus("warn","載入中",`讀取：${v632CloudPathText()}`);const snap=await tripDocRef().get();if(!snap.exists||!snap.data()?.data){if(!silent)toast("這趟旅程雲端目前沒有資料");setSyncStatus("off","雲端無資料",v632CloudPathText());return false}suppressCloudSave=true;const doc=snap.data();data=v63NormalizeData(doc.data);cur=data.days?.[0]?.key||data.trip?.start||cur;currentDay=cur;v63PersistTripLocal();lastCloudUpdatedAt=doc.updatedAtClient||v632Now();suppressCloudSave=false;cloudReady=true;render();setSyncStatus("on","已載入雲端資料",`旅程：${v63CurrentTripTitle()}`);v649ApplyLockBanner();return true}catch(err){suppressCloudSave=false;const msg=err?.message||String(err);setSyncStatus("off","載入雲端失敗",msg);if(!silent)alert("載入雲端失敗："+msg);return false}}

/* listenCloudChanges */
function listenCloudChanges(){if(!v632CanUseCloud(false))return;if(cloudUnsub){cloudUnsub();cloudUnsub=null}const listeningTripId=currentTripId;cloudUnsub=tripDocRef().onSnapshot(snap=>{if(!snap.exists||!snap.data()?.data||!cloudReady)return;if(listeningTripId!==currentTripId)return;const doc=snap.data();const remoteUpdated=doc.updatedAtClient||0;const localMeta=v632GetLocalMeta(currentTripId);const localUpdated=localMeta.updatedAtClient||0;if(remoteUpdated&&remoteUpdated>Math.max(lastCloudUpdatedAt,localUpdated)+1200){lastCloudUpdatedAt=remoteUpdated;setSyncStatus("warn","雲端有較新的資料","可按「載入」更新此裝置")}},err=>setSyncStatus("off","雲端監聽失敗",err.message))}

/* ── v63 多旅程系統 ── */
function loadData(){try{const raw=currentTripId?localStorage.getItem(getLocalTripKey(currentTripId)):null;const fallback=localStorage.getItem("travel_book_v12")||localStorage.getItem("travel_book_v8")||localStorage.getItem("travel_book_v7");const s=JSON.parse(raw||fallback||"{}");return v63NormalizeData(s)}catch(e){return v63CloneBase()}}
async function v632SaveTripIndexCloud(){if(!fbUser||!fbDb)return;try{await v63TripIndexRef().set({trips:tripList,updatedAtClient:v632Now(),ownerEmail:fbUser.email||"",appVersion:APP_VERSION},{merge:true})}catch(e){console.warn("tripIndex save failed",e);throw e}}
function initFirebaseSync(){if(!window.firebase){setSyncStatus("off","Firebase SDK 尚未載入","請確認網路連線。");return}if(!firebase.apps.length)fbApp=firebase.initializeApp(FIREBASE_CONFIG);else fbApp=firebase.app();fbAuth=firebase.auth();fbDb=firebase.firestore();fbAuth.onAuthStateChanged(v63HandleAuth)}

/* ── init（主初始化） ── */
