/* ── stay.js ── */

function v15CountryCityMaps(){return{cityMap:{"韓國":["釜山","首爾","濟州","大邱","仁川","自訂"],"日本":["東京","大阪","京都","福岡","札幌","沖繩","名古屋","自訂"],"中國":["上海","北京","廣州","深圳","杭州","成都","重慶","西安","青島","廈門","南京","蘇州","自訂"],"香港":["香港"],"新加坡":["新加坡"],"泰國":["曼谷","清邁","普吉","自訂"],"越南":["胡志明","河內","峴港","自訂"],"美國":["紐約","洛杉磯","舊金山","西雅圖","拉斯維加斯","自訂"],"歐洲":["自訂"],"英國":["倫敦","曼徹斯特","愛丁堡","自訂"],"其他":["自訂"]}}}
function v15DestinationName(country,city){if(country==="香港"&&(!city||city==="香港"))return"香港";if(country==="新加坡"&&(!city||city==="新加坡"))return"新加坡";if(country==="歐洲")return city?`歐洲｜${city}`:"歐洲";return[country,city].filter(Boolean).join("")}
function v15CityOptions(selected=""){const list=(v15CountryCityMaps().cityMap[$("country")?.value||data.trip.country]||["自訂"]);const safeSelected=selected&&list.includes(selected)?selected:(list[0]||"自訂");return list.map(c=>`<option value="${c}" ${c===safeSelected?"selected":""}>${c}</option>`).join("")}
function v15CurrentCity(){const city=data.trip.city||"";if(city)return city;const dest=data.trip.dest||"";const country=data.trip.country||"";const list=v15CountryCityMaps().cityMap[country]||[];return list.find(c=>dest.includes(c))||list[0]||""}
function updateCustomCityVisibility(){const box=$("customCityBox");if(!box)return;box.style.display=($("country")?.value==="其他"||$("citySelect")?.value==="自訂")?"block":"none"}
function refreshCityOptions(){const list=v15CountryCityMaps().cityMap[$("country")?.value]||[];if($("citySelect"))$("citySelect").innerHTML=v15CityOptions(list[0]||"自訂");if($("cityCustom"))$("cityCustom").value="";updateCustomCityVisibility();countryChanged()}
function handleCountrySelectChange(){refreshCityOptions()}
function updateDestByCity(){updateCustomCityVisibility();countryChanged()}
function countryChanged(){const c=$("country")?.value;if(c&&currencyMap[c]){if($("currency"))$("currency").value=currencyMap[c];if($("rateSetup"))$("rateSetup").value=rateMap[currencyMap[c]]||data.trip.rate}const label=$("rateLabel");if(label)label.textContent=`匯率：1 ${$("currency")?.value||data.trip.currency} = TWD`}
function previewTravelerCount(){let n=Number($("travelerCount").value),old=data.trip.travelers||[],html="";for(let i=0;i<n;i++)html+=`<div><label>旅伴 ${String.fromCharCode(65+i)} 名稱</label><input id="traveler${i}" value="${esc(old[i]||String.fromCharCode(65+i))}"></div>`;if($("travelerBox"))$("travelerBox").innerHTML=html}
function searchHotelAddress(){const name=$("hname")?.value;if(!name)return toast("請先輸入住宿名稱");map(encodeURIComponent(name+" "+data.trip.dest))}

/* ── v18 住宿工具 ── */
function v18SortHotels(){data.hotels.sort((a,b)=>String(a.start||"").localeCompare(String(b.start||""))||String(a.end||"").localeCompare(String(b.end||"")))}
function v18TripDefaultForCountry(country){const cityMap=v15CountryCityMaps().cityMap;const city=(cityMap[country]||[""])[0]||"";const currency=(currencyMap[country])?currencyMap[country]:"USD";const rate=(rateMap[currency])?rateMap[currency]:1;const dest=v15DestinationName(country,city);return{country,city,currency,rate,dest}}
function v18ResetTripForCountry(country){const keepMeta=data.meta||{};const keepDates={start:data.trip.start,end:data.trip.end,travelerCount:data.trip.travelerCount,travelers:[...(data.trip.travelers||["A","B"])]};const t=v18TripDefaultForCountry(country);data.meta={...keepMeta};data.trip={...data.trip,country:t.country,city:t.city,dest:t.dest,currency:t.currency,rate:t.rate,start:keepDates.start,end:keepDates.end,travelerCount:keepDates.travelerCount,travelers:keepDates.travelers};data.days=mkDays(data.trip.start,data.trip.end);data.flights={out:{},back:{}};data.hotels=[];data.expenses=[];data.spots=[];data.plans=[];data.conns=[];data.photos=[];data.dayCovers={};data.dayCoverMeta={};data.packing=pack0.map(x=>({id:uid(),type:x[0],name:x[1],note:x[2],checked:false}));data.packView="pre";cur=data.days[0]?.key||data.trip.start}
function cancelCountryReset(){v18PendingCountry=null;$("countryResetModal")?.classList.remove("show")}
function confirmCountryReset(){if(!v18PendingCountry)return;v18ResetTripForCountry(v18PendingCountry);v18PendingCountry=null;$("countryResetModal")?.classList.remove("show");save();toast("已清空資料並切換旅遊國家")}

/* ── v23 驗證工具 ── */
function v23ParseDateOnly(s){if(!s)return null;const[y,m,d]=String(s).split("-").map(Number);if(!y||!m||!d)return null;return new Date(y,m-1,d).getTime()}
function v23ParseDateTime(s){if(!s)return null;const t=new Date(s).getTime();return Number.isFinite(t)?t:null}
function v23InTripRange(dateStr){const d=v23ParseDateOnly(dateStr),s=v23ParseDateOnly(data.trip.start),e=v23ParseDateOnly(data.trip.end);return d!==null&&s!==null&&e!==null&&d>=s&&d<=e}
function v23TimeToMin(t){if(!t)return null;const[h,m]=String(t).split(":").map(Number);if(!Number.isFinite(h)||!Number.isFinite(m))return null;return h*60+m}
function v23ValidateHotelDates(start,end){if(!start||!end){alert("請填寫住宿入住日與退房日。");return false}if(!v23InTripRange(start)||!v23InTripRange(end)){alert(`住宿日期必須在旅遊日期區間內：${data.trip.start} ～ ${data.trip.end}`);return false}if(v23ParseDateOnly(end)<v23ParseDateOnly(start)){alert("住宿退房日不可早於入住日。");return false}return true}
function v23ValidatePlanForm(){const day=$("pday")?.value||"";const start=$("ps")?.value||"";const end=$("pe")?.value||"";const type=normalizePlanType($("ptype")?.value||"其他");if(!v23InTripRange(day)){alert(`行程日期必須在旅遊日期區間內：${data.trip.start} ～ ${data.trip.end}`);return false}const flexibleTypes=["交通","航班","住宿"];if(!flexibleTypes.includes(type)){if(!start||!end){alert("景點／餐廳／購物等一般行程需填寫開始與結束時間。");return false}}if(start&&end){const s=v23TimeToMin(start),e=v23TimeToMin(end);if(e<s){alert("行程結束時間不可早於開始時間。");return false}}return true}

/* ── 行程類型正規化 ── */
function normalizePlanType(type){if(!type||type==="undefined"||type==="null")return"其他";const t=String(type).trim();if(!t)return"其他";if(PLAN_TYPES.includes(t))return t;return"其他"}
function budgetTypeFromPlanType(type){const t=normalizePlanType(type);const map={"景點":"景點票券","餐廳":"餐飲","咖啡廳":"餐飲","購物":"購物","交通":"交通票券","航班":"機票","住宿":"住宿","雨天備案":"其他","其他":"其他"};return map[t]||"其他"}
function normalizeAllPlanTypes(){(data.plans||[]).forEach(p=>{p.type=normalizePlanType(p.type)})}
function optsPlanTypes(selected="景點"){const safe=normalizePlanType(selected);return PLAN_TYPES.map(t=>`<option value="${t}" ${safe===t?"selected":""}>${t}</option>`).join("")}
function v28PlanId(prefix,parts){return[prefix].concat(parts||[]).map(x=>String(x||"").replace(/[^\w\u4e00-\u9fa5-]/g,"-")).join("-")}
function v28NormalizeSourceFromLegacy(p){if(p.source)return p.source;if(p.sourceType==="flight"||p.memo==="由航班資料帶入")return"flight";if(p.sourceType==="hotel"||p.hotelId||p.memo==="由住宿資料帶入")return"hotel";return"manual"}
function v28NormalizePlans(){const seen=new Set();(data.plans||[]).forEach(p=>{if(!p.id)p.id=uid();if(seen.has(p.id))p.id=uid();seen.add(p.id);p.source=v28NormalizeSourceFromLegacy(p);if(!p.sourceType&&p.source!=="manual")p.sourceType=p.source;if(!p.type||p.type==="undefined")p.type=normalizePlanType(p.type)})}
function v28UpsertPlan(plan){if(!plan||!plan.id)return null;plan.type=normalizePlanType(plan.type);plan.source=plan.source||"manual";if(plan.source!=="manual")plan.sourceType=plan.source;const existing=data.plans.find(p=>p.id===plan.id);if(existing){const keepNote=existing.note,keepMemo=existing.memo;Object.assign(existing,plan);if(keepNote&&keepNote!==plan.note)existing.note=keepNote;if(keepMemo&&keepMemo!==plan.memo)existing.memo=keepMemo;existing.source=plan.source;existing.sourceType=plan.sourceType||plan.source;existing.lockedName=plan.lockedName??existing.lockedName;return existing.id}else{const newPlan={mode:"foreign",foreign:0,twd:0,payer:"未定",payMethod:"未定",note:"",memo:"",adjusted:false,...plan};data.plans.push(newPlan);createBudgetFromPlanSnapshot(newPlan);return newPlan.id}}
function v28DeletePlansBySource(source,predicate){const removedIds=data.plans.filter(p=>p.source===source&&(!predicate||predicate(p))).map(p=>p.id);data.plans=data.plans.filter(p=>!removedIds.includes(p.id));data.conns=(data.conns||[]).filter(c=>!removedIds.includes(c.a)&&!removedIds.includes(c.b))}
function v16DateAdd(dateStr,days){const[y,m,d]=dateStr.split("-").map(Number);const dt=new Date(y,m-1,d);dt.setDate(dt.getDate()+days);return`${dt.getFullYear()}-${String(dt.getMonth()+1).padStart(2,"0")}-${String(dt.getDate()).padStart(2,"0")}`}
function v16DateRange(start,endInclusive){if(!start||!endInclusive)return[];const arr=[];let d=start;while(d<=endInclusive){arr.push(d);d=v16DateAdd(d,1)}return arr}
function v16ParseDate(s){if(!s)return null;const[y,m,d]=s.split("-").map(Number);return new Date(y,m-1,d)}
function v16DateFromDT(dt){return dt?String(dt).split("T")[0]:""}
function v16TimeFromDT(dt){return dt&&String(dt).includes("T")?String(dt).split("T")[1].slice(0,5):""}
function v16PlanExists(day,name,start){return data.plans.some(p=>p.day===day&&p.name===name&&p.start===start)}
function v16AddPlanNode(item){if(!item.day||!item.name)return null;item.type=normalizePlanType(item.type);if(v16PlanExists(item.day,item.name,item.start))return null;const plan={id:uid(),mode:"foreign",foreign:0,twd:0,payer:"未定",payMethod:"未定",note:"",memo:"",adjusted:false,...item};plan.type=normalizePlanType(plan.type);data.plans.push(plan);createBudgetFromPlanSnapshot(plan);return plan.id}
function v16OpenTripDetail(index){const details=document.querySelectorAll("#stayView details.card");if(details[index])details[index].setAttribute("open","")}
function v16CollapseTripDetail(index){const details=document.querySelectorAll("#stayView details.card");if(details[index])details[index].removeAttribute("open")}
function v16AddHotelToPlans(h){if(!h.start||!h.end||!h.name)return;v16AddPlanNode({hotelId:h.id,sourceType:"hotel",source:"hotel",lockedName:true,day:h.start,start:"15:00",end:"15:30",type:"住宿",name:`入住 ${h.name}`,note:h.addr||h.note||"",memo:"由住宿資料帶入"});v16DateRange(v16DateAdd(h.start,1),h.end).forEach(day=>{v16AddPlanNode({hotelId:h.id,sourceType:"hotel",source:"hotel",lockedName:true,day,start:"09:00",end:"09:10",type:"住宿",name:`從 ${h.name} 出發`,note:h.addr||"",memo:"由住宿資料帶入"})});v16DateRange(h.start,v16DateAdd(h.end,-1)).forEach(day=>{v16AddPlanNode({hotelId:h.id,sourceType:"hotel",source:"hotel",lockedName:true,day,start:"21:00",end:"21:10",type:"住宿",name:`回到 ${h.name}`,note:h.addr||"",memo:"由住宿資料帶入"})})}

/* ── 住宿 CRUD ── */
function hotelHasPlans(id){v28NormalizePlans();return data.plans.some(p=>p.source==="hotel"&&p.hotelId==id)}
function hotelHasExpense(id){return data.expenses.some(e=>e.hotelId==id)}
function hotelPlanTemplates(h){if(!h||!h.id||!h.start||!h.end||!h.name)return[];const arr=[];arr.push({id:v28PlanId("hotel",[h.id,"checkin",h.start]),source:"hotel",sourceType:"hotel",hotelId:h.id,lockedName:true,day:h.start,start:"15:00",end:"15:30",type:"住宿",name:`入住 ${h.name}`,note:h.addr||h.note||"",memo:"由住宿資料帶入"});v16DateRange(v16DateAdd(h.start,1),h.end).forEach(day=>{arr.push({id:v28PlanId("hotel",[h.id,"morning",day]),source:"hotel",sourceType:"hotel",hotelId:h.id,lockedName:true,day,start:"09:00",end:"09:10",type:"住宿",name:`從 ${h.name} 出發`,note:h.addr||"",memo:"由住宿資料帶入"})});v16DateRange(h.start,v16DateAdd(h.end,-1)).forEach(day=>{arr.push({id:v28PlanId("hotel",[h.id,"night",day]),source:"hotel",sourceType:"hotel",hotelId:h.id,lockedName:true,day,start:"21:00",end:"21:10",type:"住宿",name:`回到 ${h.name}`,note:h.addr||"",memo:"由住宿資料帶入"})});return arr}
function addHotelPlans(id){const h=data.hotels.find(x=>x.id==id);if(!h)return;v28NormalizePlans();v28DeletePlansBySource("hotel",p=>p.hotelId==id);hotelPlanTemplates(h).forEach(p=>v28UpsertPlan(p));save();toast("已幫你同步住宿行程！")}
function removeHotelPlans(id){v28DeletePlansBySource("hotel",p=>p.hotelId==id);save();toast("已移除住宿行程")}
function addHotelExpense(id){const h=data.hotels.find(x=>x.id==id);if(!h)return;if(hotelHasExpense(id))return toast("這間住宿已帶入預算");data.expenses.push({id:uid(),hotelId:id,source:"住宿",type:"住宿",name:`${short(h.start)}~${short(h.end)} ${h.name}`,payer:"未定",payMethod:"未定",day:"",mode:"TWD",foreign:0,twd:0,memo:"由住宿資料帶入，可編輯金額"});save();toast("已帶入住宿預算")}
function removeHotelExpense(id){data.expenses=data.expenses.filter(e=>e.hotelId!=id);save();toast("已移除住宿預算")}
function hotelCard(h){const hasP=hotelHasPlans(h.id),hasE=hotelHasExpense(h.id);return`<div class="card"><div class="time">${short(h.start)}→${short(h.end)}</div><div class="place">🏨 ${esc(h.name)}</div><div class="box mint">${esc(h.addr||"尚未填地址")}<br>${esc(h.note||"")}</div><div class="hotelActionState">${hasP?'<span class="tag">已帶入行程</span>':'<span class="tag">未帶入行程</span>'}${hasE?'<span class="tag">已帶入預算</span>':'<span class="tag">未帶入預算</span>'}</div><div class="btns"><button class="small" onclick="editHotel('${h.id}')">編輯</button><button class="small" onclick="map('${encodeURIComponent((h.addr||h.name)+" "+data.trip.dest)}')">地圖</button>${hasP?`<button class="small" onclick="removeHotelPlans('${h.id}')">移除行程</button>`:`<button class="small" onclick="addHotelPlans('${h.id}')">帶入行程</button>`}${hasE?`<button class="small" onclick="removeHotelExpense('${h.id}')">移除預算</button>`:`<button class="small" onclick="addHotelExpense('${h.id}')">帶入預算</button>`}<button class="small" onclick="delHotel('${h.id}')">刪除</button></div></div>`}
function editHotel(id){editingHotelId=id;v16KeepHotelOpen=true;go("stay")}
function delHotel(id){data.hotels=data.hotels.filter(h=>h.id!=id);v28DeletePlansBySource("hotel",p=>p.hotelId==id);save()}
function closeHotelOptions(){v21PendingHotelId=null;$("hotelOptionModal")?.classList.remove("show");toast("已新增住宿")}
function confirmHotelOptions(){const id=v21PendingHotelId;if(!id)return closeHotelOptions();if($("hotelOptionAddPlans")?.checked)addHotelPlans(id);if($("hotelOptionAddBudget")?.checked)addHotelExpense(id);v21PendingHotelId=null;$("hotelOptionModal")?.classList.remove("show");toast("已完成住宿同步設定")}

/* ── 航班工具 (normalizeFlightObj + flightSegment + flightForm v646) ── */
function airportOptionsList(){return["台灣｜TPE 桃園國際機場","台灣｜TSA 台北松山機場","台灣｜KHH 高雄小港機場","台灣｜RMQ 台中國際機場","韓國｜PUS 釜山金海機場","韓國｜ICN 首爾仁川機場","韓國｜GMP 首爾金浦機場","日本｜NRT 東京成田機場","日本｜HND 東京羽田機場","日本｜KIX 大阪關西機場","日本｜FUK 福岡機場","日本｜CTS 札幌新千歲機場","日本｜NGO 名古屋中部機場","香港｜HKG 香港國際機場","新加坡｜SIN 樟宜機場","泰國｜BKK 曼谷蘇凡納布機場","泰國｜DMK 曼谷廊曼機場","越南｜SGN 胡志明新山一機場","越南｜HAN 河內內排機場","馬來西亞｜KUL 吉隆坡國際機場","菲律賓｜MNL 馬尼拉機場","澳門｜MFM 澳門國際機場","中國｜PVG 上海浦東機場","中國｜SHA 上海虹橋機場","中國｜PEK 北京首都機場","中國｜PKX 北京大興機場","中國｜CAN 廣州白雲機場","中國｜SZX 深圳寶安機場","美國｜LAX 洛杉磯機場","美國｜SFO 舊金山機場","美國｜JFK 紐約甘迺迪機場","歐洲｜LHR 倫敦希斯洛機場","歐洲｜CDG 巴黎戴高樂機場","歐洲｜FRA 法蘭克福機場","歐洲｜AMS 阿姆斯特丹史基浦機場","歐洲｜VIE 維也納機場","歐洲｜PRG 布拉格機場"]}
function airportDatalistHtml(){return`<datalist id="airportList">${airportOptionsList().map(a=>`<option value="${esc(a)}"></option>`).join("")}</datalist>`}
function terminalOptions(selected=""){const opts=["未定","T1","T2","T3","T4","T5","國際線航廈","國內線航廈","第一航廈","第二航廈","第三航廈","Satellite / 衛星航廈","其他"];const safe=selected||"未定";return opts.map(x=>`<option value="${x}" ${String(safe)===x?"selected":""}>${x}</option>`).join("")}
function normalizeFlightObj(f,direction){f=f||{};if(Array.isArray(f.segments)&&f.segments.length){const normalizedSegments=f.segments.map(s=>({no:s.no||"",from:s.from||"",to:s.to||"",dep:s.dep||"",arr:s.arr||"",fromTerminal:s.fromTerminal||"",toTerminal:s.toTerminal||""}));return{type:f.type||(normalizedSegments.length>1?"transfer":"direct"),segments:normalizedSegments,toAirport:f.toAirport||"",fromAirport:f.fromAirport||"",transfer:f.transfer||""}}return{type:"direct",segments:[{no:f.no||"",from:f.from||"",to:f.to||"",dep:f.dep||"",arr:f.arr||"",fromTerminal:f.fromTerminal||"",toTerminal:f.toTerminal||""}],toAirport:f.toAirport||f.transfer||"",fromAirport:f.fromAirport||"",transfer:f.transfer||""}}
function flightTypeSelect(k,selected){return`<select id="${k}type" onchange="toggleFlightSegments('${k}')"><option value="direct" ${selected==="direct"?"selected":""}>直飛</option><option value="transfer" ${selected==="transfer"?"selected":""}>轉機</option></select>`}

/* v646 最終版 flightSegmentForm：使用 details + 桌機/手機雙模式 */
function flightSegmentForm(k,idx,seg){seg=seg||{};const defaultOpen=idx===0?"open":"";return`<details class="segmentBox" id="${k}segBox${idx}" ${defaultOpen}><summary><div class="segmentTitle">第 ${idx+1} 段航班 <span>${idx===0?"第一段":"第二段／轉機後"}</span></div></summary><div class="segmentInner"><div class="three compactMobile"><div><label>航班號</label><input id="${k}s${idx}no" value="${esc(seg.no||"")}" placeholder="例：BX794"></div><div><label>出發地 / 機場</label><input id="${k}s${idx}from" list="airportList" value="${esc(seg.from||"")}" placeholder="可選清單或自行輸入"></div><div><label>抵達地 / 機場</label><input id="${k}s${idx}to" list="airportList" value="${esc(seg.to||"")}" placeholder="可選清單或自行輸入"></div></div><div class="terminalPair"><div><label>出發航廈</label><select id="${k}s${idx}fromTerminal">${terminalOptions(seg.fromTerminal||"未定")}</select></div><div><label>抵達航廈</label><select id="${k}s${idx}toTerminal">${terminalOptions(seg.toTerminal||"未定")}</select></div></div><div class="two"><div><label>起飛時間</label><input id="${k}s${idx}dep" type="datetime-local" value="${seg.dep||""}"></div><div><label>抵達時間</label><input id="${k}s${idx}arr" type="datetime-local" value="${seg.arr||""}"></div></div><div class="airportQuickHint">台灣與亞洲機場優先列出；找不到可手動輸入。</div></div></details>`}

/* v646 最終版 flightForm：直飛只顯示第 1 段 */
function flightForm(k){const f=normalizeFlightObj(data.flights[k],k);const segs=[f.segments[0]||{},f.segments[1]||{}];const isOut=k==="out";const type=f.type||"direct";return`<div class="flightTransferBlock" data-flight-dir="${k}" data-flight-type="${type}">${airportDatalistHtml()}<label>航班型態</label>${flightTypeSelect(k,type)}<div class="flightTypeHint">直飛只填第 1 段；轉機時才會顯示第 2 段航班。</div><div id="${k}segmentsWrap">${flightSegmentForm(k,0,segs[0])}<div class="${type==="transfer"?"":"v646-hidden-segment"}" id="${k}segExtraWrap1">${flightSegmentForm(k,1,segs[1])}</div></div><label>${isOut?"抵達出發機場方式":"前往回程機場方式"}</label><textarea id="${k}toAirport" placeholder="${isOut?"例：14:00 從家出發，搭機捷到桃園機場":"例：從飯店搭地鐵／計程車到機場"}">${esc(f.toAirport||f.transfer||"")}</textarea><label>${isOut?"降落後到市區／飯店":"抵達後回家方式"}</label><textarea id="${k}fromAirport" placeholder="${isOut?"例：金海機場搭輕軌轉地鐵到飯店":"例：抵達桃園後搭機捷／接送回家"}">${esc(f.fromAirport||"")}</textarea></div>`}

/* v646 最終版 toggleFlightSegments */
function toggleFlightSegments(k){const type=$(k+"type")?.value||normalizeFlightObj(data.flights[k],k).type||"direct";const wrap=document.querySelector(`[data-flight-dir="${k}"]`);if(wrap)wrap.setAttribute("data-flight-type",type);const extra=$(k+"segExtraWrap1")||$(k+"segBox1");if(extra){extra.classList.toggle("v646-hidden-segment",type!=="transfer");if(extra.style)extra.style.display=type==="transfer"?"":"none"}}
function readFlightForm(k){const type=$(k+"type")?.value||"direct";const count=type==="transfer"?2:1;const segments=[];for(let i=0;i<count;i++){segments.push({no:$(k+"s"+i+"no")?.value||"",from:$(k+"s"+i+"from")?.value||"",to:$(k+"s"+i+"to")?.value||"",dep:$(k+"s"+i+"dep")?.value||"",arr:$(k+"s"+i+"arr")?.value||"",fromTerminal:$(k+"s"+i+"fromTerminal")?.value||"",toTerminal:$(k+"s"+i+"toTerminal")?.value||""})}return{type,segments,toAirport:$(k+"toAirport")?.value||"",fromAirport:$(k+"fromAirport")?.value||"",transfer:$(k+"toAirport")?.value||""}}
function terminalNote(s){const fromT=s.fromTerminal&&s.fromTerminal!=="未定"?`出發航廈：${s.fromTerminal}`:"";const toT=s.toTerminal&&s.toTerminal!=="未定"?`抵達航廈：${s.toTerminal}`:"";return[fromT,toT].filter(Boolean).join("｜")}
function validateFlightSegments(){const out=readFlightForm("out"),back=readFlightForm("back");const all=[...out.segments.map((s,i)=>({dir:"去程",idx:i+1,...s})),...back.segments.map((s,i)=>({dir:"回程",idx:i+1,...s}))];for(const s of all){const missing=[];if(!s.no)missing.push("航班號");if(!s.from)missing.push("出發地");if(!s.to)missing.push("抵達地");if(!s.dep)missing.push("起飛時間");if(!s.arr)missing.push("抵達時間");if(missing.length){alert(`${s.dir}第 ${s.idx} 段請填完整：${missing.join("、")}`);return false}const dep=v23ParseDateTime(s.dep),arr=v23ParseDateTime(s.arr);if(!(dep<arr)){alert(`${s.dir}第 ${s.idx} 段的抵達時間需晚於起飛時間。`);return false}const depDay=String(s.dep).split("T")[0],arrDay=String(s.arr).split("T")[0];if(!v23InTripRange(depDay)||!v23InTripRange(arrDay)){alert(`${s.dir}第 ${s.idx} 段航班日期需落在旅遊日期區間內：${data.trip.start} ～ ${data.trip.end}`);return false}}for(let i=1;i<all.length;i++){const prevArr=v23ParseDateTime(all[i-1].arr),curDep=v23ParseDateTime(all[i].dep);if(!(prevArr<curDep)){alert("請確認航班時間順序：每一段航班的起飛時間都必須晚於上一段的抵達時間。");return false}}return true}

/* ── v39 航班時間工具 ── */
function v39Pad(n){return String(n).padStart(2,"0")}
function v39ParseLocalDT(dt){if(!dt)return null;const[d,t]=String(dt).split("T");if(!d||!t)return null;const[y,m,day]=d.split("-").map(Number);const[hh,mm]=t.split(":").map(Number);if(!y||!m||!day||!Number.isFinite(hh)||!Number.isFinite(mm))return null;return new Date(y,m-1,day,hh,mm,0,0)}
function v39FormatDate(d){if(!d)return"";return`${d.getFullYear()}-${v39Pad(d.getMonth()+1)}-${v39Pad(d.getDate())}`}
function v39FormatTime(d){if(!d)return"";return`${v39Pad(d.getHours())}:${v39Pad(d.getMinutes())}`}
function v39AddMinutes(dt,minutes){const d=v39ParseLocalDT(dt);if(!d)return null;return new Date(d.getTime()+minutes*60000)}
function v39DateFromDT(dt,fallback){const d=v39ParseLocalDT(dt);return d?v39FormatDate(d):(fallback||data.trip.start)}
function v39TimeFromDT(dt){const d=v39ParseLocalDT(dt);return d?v39FormatTime(d):""}
function v39DateFromDateObj(d,fallback){return d?v39FormatDate(d):(fallback||data.trip.start)}
function v39TimeFromDateObj(d){return d?v39FormatTime(d):""}
function v39SavedFlightReady(){const out=normalizeFlightObj(data.flights.out,"out"),back=normalizeFlightObj(data.flights.back,"back");const all=[...(out.segments||[]),...(back.segments||[])];if(!all.length)return false;return all.every(s=>s.no&&s.from&&s.to&&s.dep&&s.arr)}
function v39FlightSnapshotFromData(){return JSON.stringify({out:normalizeFlightObj(data.flights.out,"out"),back:normalizeFlightObj(data.flights.back,"back")})}
function v39FlightSnapshotFromForm(){try{return JSON.stringify({out:readFlightForm("out"),back:readFlightForm("back")})}catch(e){return""}}
function v39MarkFlightDirty(){const formSig=v39FlightSnapshotFromForm(),dataSig=v39FlightSnapshotFromData();v39FlightDirty=!!formSig&&formSig!==dataSig;v39RenderFlightStatusOnly()}
function v39CanUseFlightActions(){return!v39FlightDirty&&v39SavedFlightReady()}
function v39FlightName(direction,idx,segCount,no){const isOut=direction==="out";if(segCount<=1){return isOut?`搭乘去程飛機${no?" "+no:""}`:isOut==="out"?`搭乘去程飛機${no?" "+no:""}`:` 搭乘回程飛機${no?" "+no:""}`}return isOut?`搭乘去程第 ${idx+1} 段飛機${no?" "+no:""}`:` 搭乘回程第 ${idx+1} 段飛機${no?" "+no:""}`}

/* ── 航班行程模板 (v39 最終版) ── */
function flightPlanTemplates(){const out=normalizeFlightObj(data.flights.out,"out"),back=normalizeFlightObj(data.flights.back,"back"),templates=[];const outSegs=(out.segments&&out.segments.length?out.segments:[{}]);const backSegs=(back.segments&&back.segments.length?back.segments:[{}]);const firstOut=outSegs[0]||{},lastOut=outSegs[outSegs.length-1]||{},firstBack=backSegs[0]||{},lastBack=backSegs[backSegs.length-1]||{};const outAirportArrive=v39AddMinutes(firstOut.dep,-120);const outCityEnd=v39AddMinutes(lastOut.arr,60);const backAirportArrive=v39AddMinutes(firstBack.dep,-120);const backHomeEnd=v39AddMinutes(lastBack.arr,60);templates.push({id:"flight-out-to-airport",source:"flight",sourceType:"flight",lockedName:true,day:v39DateFromDateObj(outAirportArrive,v39DateFromDT(firstOut.dep,data.trip.start)),start:"",end:v39TimeFromDateObj(outAirportArrive),type:"交通",name:`出發去 ${firstOut.from||"機場"}`,note:out.toAirport||"",memo:"由航班資料帶入"});outSegs.forEach((s,i)=>{templates.push({id:`flight-out-seg-${i}`,source:"flight",sourceType:"flight",lockedName:true,day:v39DateFromDT(s.dep,data.trip.start),start:v39TimeFromDT(s.dep),end:v39TimeFromDT(s.arr),type:"航班",name:v39FlightName("out",i,outSegs.length,s.no||""),note:[`${s.from||""} → ${s.to||""}`,terminalNote(s)].filter(Boolean).join("\n"),memo:"由航班資料帶入"})});templates.push({id:"flight-out-arrival-transfer",source:"flight",sourceType:"flight",lockedName:true,day:v39DateFromDT(lastOut.arr,data.trip.start),start:v39TimeFromDT(lastOut.arr),end:v39TimeFromDateObj(outCityEnd),type:"交通",name:`從 ${lastOut.to||"抵達機場"} 前往市區／飯店`,note:out.fromAirport||"",memo:"由航班資料帶入"});templates.push({id:"flight-back-to-airport",source:"flight",sourceType:"flight",lockedName:true,day:v39DateFromDateObj(backAirportArrive,v39DateFromDT(firstBack.dep,data.trip.end)),start:"",end:v39TimeFromDateObj(backAirportArrive),type:"交通",name:`從飯店前往 ${firstBack.from||"回程機場"}`,note:back.toAirport||"",memo:"由航班資料帶入"});backSegs.forEach((s,i)=>{templates.push({id:`flight-back-seg-${i}`,source:"flight",sourceType:"flight",lockedName:true,day:v39DateFromDT(s.dep,data.trip.end),start:v39TimeFromDT(s.dep),end:v39TimeFromDT(s.arr),type:"航班",name:v39FlightName("back",i,backSegs.length,s.no||""),note:[`${s.from||""} → ${s.to||""}`,terminalNote(s)].filter(Boolean).join("\n"),memo:"由航班資料帶入"})});templates.push({id:"flight-back-home-transfer",source:"flight",sourceType:"flight",lockedName:true,day:v39DateFromDT(lastBack.arr,data.trip.end),start:v39TimeFromDT(lastBack.arr),end:v39TimeFromDateObj(backHomeEnd),type:"交通",name:`從 ${lastBack.to||"抵達機場"} 回家`,note:back.fromAirport||"",memo:"由航班資料帶入"});return templates}
function syncFlightPlans(){v28NormalizePlans();const templates=flightPlanTemplates();const keepIds=templates.map(p=>p.id);data.plans=data.plans.filter(p=>p.source!=="flight"||keepIds.includes(p.id));data.conns=(data.conns||[]).filter(c=>data.plans.some(p=>p.id===c.a)&&data.plans.some(p=>p.id===c.b));templates.forEach(p=>v28UpsertPlan(p))}
function v16AddFlightsToPlans(doRender=true){if(!v39CanUseFlightActions()){toast(v39FlightDirty?"請先存好航班設定":"請先填寫並存好航班");return}syncFlightPlans();if(doRender)save();toast("已幫你把航班帶入行程囉！")}
function removeFlightPlans(){v28DeletePlansBySource("flight");save();toast("已幫你移除航班行程囉！")}
function addFlightBudget(){if(!v39CanUseFlightActions()){toast(v39FlightDirty?"請先存好航班設定":"請先填寫並存好航班");return}if(flightHasBudget())return toast("航班預算已經記過囉！");const out=normalizeFlightObj(data.flights.out,"out"),back=normalizeFlightObj(data.flights.back,"back");const outNos=out.segments.map(s=>s.no).filter(Boolean).join("＋");const backNos=back.segments.map(s=>s.no).filter(Boolean).join("＋");const label=[outNos?`去程 ${outNos}`:"",backNos?`回程 ${backNos}`:""].filter(Boolean).join("／");data.expenses.push({id:uid(),sourceType:"flight",source:"航班",type:"機票",name:label?`來回機票（${label}）`:"來回機票",payer:"未定",payMethod:"未定",day:"",mode:"TWD",foreign:0,twd:0,memo:"由航班資料帶入，可自行補金額"});save();toast("已幫你記一筆來回機票！")}
function removeFlightBudget(){data.expenses=data.expenses.filter(e=>!(e.sourceType==="flight"||e.source==="航班"));save();toast("已幫你移除航班預算囉！")}

/* v39 最終版 saveFlights */
function flightStatusInnerHtml(){const hasP=flightHasPlans(),hasB=flightHasBudget(),canUse=v39CanUseFlightActions();const stateText=v39FlightDirty?"有尚未儲存的航班修改":(v39SavedFlightReady()?"航班已儲存":"請先填寫並存好航班");const stateClass=v39FlightDirty?"warn":(v39SavedFlightReady()?"":"off");const disabledAttr=canUse?"":"disabled";const actionHint=v39FlightDirty?"請先按「存好航班設定」，再帶入行程或預算。":(v39SavedFlightReady()?"可選擇是否帶入行程或記一筆來回機票。":"航班資料存好後，才會開放帶入行程與預算。");return`<div class="flightSavedHint"><span class="flightStatusSaved ${stateClass}">${stateText}</span><br>${actionHint}</div><div class="flightStatusGrid"><div class="flightStatusItem"><b>行程</b><span class="${hasP?"ok":""}">${hasP?"已帶入行程":"尚未帶入行程"}</span></div><div class="flightStatusItem"><b>機票預算</b><span class="${hasB?"ok":""}">${hasB?"已記錄預算":"尚未記錄預算"}</span></div></div><div class="flightStatusActions">${hasP?`<button class="btn soft compact" ${disabledAttr} onclick="removeFlightPlans()">移除航班行程</button>`:`<button class="btn blue compact" ${disabledAttr} onclick="v16AddFlightsToPlans(true)">帶入行程</button>`}${hasB?`<button class="btn soft compact" ${disabledAttr} onclick="removeFlightBudget()">移除機票預算</button>`:`<button class="btn pink compact" ${disabledAttr} onclick="addFlightBudget()">記一筆來回機票</button>`}</div>`}
function flightStatusHtml(){return`<div class="flightStatusBox" id="flightStatusMount">${flightStatusInnerHtml()}</div>`}
function v39RenderFlightStatusOnly(){const mount=$("flightStatusMount");if(mount)mount.innerHTML=flightStatusInnerHtml()}

/* v21 modal 控制 */
function closeFlightOptions(){v21PendingFlightOptions=false;$("flightOptionModal")?.classList.remove("show");toast("已儲存航班")}
function confirmFlightOptions(){if($("flightOptionAddPlans")?.checked){v16AddFlightsToPlans(false);silentSave();render();toast("已儲存航班並加入首尾行程")}else toast("已儲存航班");v21PendingFlightOptions=false;$("flightOptionModal")?.classList.remove("show")}

/* ── 行程計劃 CRUD ── */
function v643ReadTripBasicFromForm(){const selectedCountry=$("country")?.value||data.trip.country||"";const cityEl=$("citySelect");let selectedCity=cityEl?cityEl.value:(data.trip.city||"");let city=selectedCity;if(selectedCity==="自訂"&&$("cityCustom"))city=$("cityCustom").value.trim();const dest=(typeof v15DestinationName==="function")?v15DestinationName(selectedCountry,city):(($("dest")?.value||data.trip.dest||"").trim());const count=Number($("travelerCount")?.value||data.trip.travelerCount||1);const travelers=[];for(let i=0;i<count;i++)travelers.push($("traveler"+i)?.value||data.trip.travelers?.[i]||String.fromCharCode(65+i));return{country:selectedCountry,city,dest,currency:($("currency")?.value||data.trip.currency||"").toUpperCase(),rate:Number($("rateSetup")?.value||data.trip.rate||1),travelerCount:count,travelers,start:$("start")?.value||data.trip.start||"",end:$("end")?.value||data.trip.end||""}}
function v643ApplyBasicFields(basic){if(!basic)return;data.trip.country=basic.country;data.trip.city=basic.city;data.trip.dest=basic.dest;data.trip.currency=basic.currency;data.trip.rate=basic.rate;data.trip.travelerCount=basic.travelerCount;data.trip.travelers=basic.travelers}
function v643DaysBetween(a,b){if(!a||!b)return 0;const d1=parseLocalDate(a),d2=parseLocalDate(b);return Math.round((d2-d1)/86400000)}
function v643ShiftDate(value,offset){if(!value||!/^\d{4}-\d{2}-\d{2}$/.test(String(value)))return value;const d=parseLocalDate(value);d.setDate(d.getDate()+Number(offset||0));return formatLocalDate(d)}
function v643ShiftDateTime(value,offset){if(!value||!/^\d{4}-\d{2}-\d{2}T/.test(String(value)))return value;return v643ShiftDate(value.slice(0,10),offset)+value.slice(10)}
function v643WithinRange(day,start,end){if(!day||!start||!end)return true;return day>=start&&day<=end}
function v643OutOfRangeCounts(start,end){const out={plans:0,spots:0,expenses:0,photos:0,covers:0,hotels:0,total:0};(data.plans||[]).forEach(x=>{if(x.day&&!v643WithinRange(x.day,start,end))out.plans++});(data.spots||[]).forEach(x=>{if(x.day&&!v643WithinRange(x.day,start,end))out.spots++});(data.expenses||[]).forEach(x=>{if(x.day&&!v643WithinRange(x.day,start,end))out.expenses++});(data.photos||[]).forEach(x=>{if(x.day&&!v643WithinRange(x.day,start,end))out.photos++});Object.keys(data.dayCovers||{}).forEach(k=>{if(!v643WithinRange(k,start,end))out.covers++});(data.hotels||[]).forEach(h=>{if((h.start&&!v643WithinRange(h.start,start,end))||(h.end&&!v643WithinRange(h.end,start,end)))out.hotels++});out.total=out.plans+out.spots+out.expenses+out.photos+out.covers+out.hotels;return out}
function v643ShiftTripDateData(offset){if(!offset)return;(data.plans||[]).forEach(x=>{if(x.day)x.day=v643ShiftDate(x.day,offset)});(data.spots||[]).forEach(x=>{if(x.day)x.day=v643ShiftDate(x.day,offset)});(data.expenses||[]).forEach(x=>{if(x.day)x.day=v643ShiftDate(x.day,offset)});(data.photos||[]).forEach(x=>{if(x.day)x.day=v643ShiftDate(x.day,offset)});(data.hotels||[]).forEach(h=>{if(h.start)h.start=v643ShiftDate(h.start,offset);if(h.end)h.end=v643ShiftDate(h.end,offset)});if(data.dayCovers){const next={};Object.keys(data.dayCovers).forEach(k=>{next[v643ShiftDate(k,offset)]=data.dayCovers[k]});data.dayCovers=next}if(data.dayCoverMeta){const next={};Object.keys(data.dayCoverMeta).forEach(k=>{next[v643ShiftDate(k,offset)]=data.dayCoverMeta[k]});data.dayCoverMeta=next}if(data.flights){["out","back"].forEach(k=>{if(data.flights[k]){if(Array.isArray(data.flights[k].segments)){data.flights[k].segments.forEach(s=>{s.dep=v643ShiftDateTime(s.dep,offset);s.arr=v643ShiftDateTime(s.arr,offset)})}else{data.flights[k].dep=v643ShiftDateTime(data.flights[k].dep,offset);data.flights[k].arr=v643ShiftDateTime(data.flights[k].arr,offset)}}})}cur=v643ShiftDate(cur,offset);if(window.currentDay)currentDay=v643ShiftDate(currentDay,offset)}
function v643EnsureDateModal(){let modal=$("dateResetModal");if(!modal){modal=document.createElement("div");modal.id="dateResetModal";modal.className="resetModal";document.body.appendChild(modal)}modal.className="resetModal v643DateModal";return modal}
function v643DateSummaryHtml(){const p=v643PendingBasic;if(!p)return"";const oldStart=data.trip.start||"",oldEnd=data.trip.end||"";const oldDays=(data.days||mkDays(oldStart,oldEnd)||[]).length;const newDays=mkDays(p.start,p.end).length;const deltaStart=v643DaysBetween(oldStart,p.start);const out=v643OutOfRangeCounts(p.start,p.end);const moveText=deltaStart===0?"起始日沒有改變，通常選「增減天數」即可。":`起始日變動 ${deltaStart>0?"往後":"往前"} ${Math.abs(deltaStart)} 天，可選「整趟平移」。`;const outText=out.total?`新日期範圍外目前有 ${out.total} 筆資料，系統會保留，不會刪除。`:"目前看起來沒有資料落在新日期範圍外。";return`<div class="v643DateCompare"><div><span>原日期</span><b>${esc(oldStart||"未設定")} ～ ${esc(oldEnd||"未設定")}</b><small>${oldDays||0} 天</small></div><div><span>新日期</span><b>${esc(p.start||"未設定")} ～ ${esc(p.end||"未設定")}</b><small>${newDays||0} 天</small></div></div><div class="box mint v643SafeNote"><b>這次不會清空資料。</b><br>${esc(outText)}<br>${esc(moveText)}</div>`}
function v643OpenDateAdjustModal(){const modal=v643EnsureDateModal();modal.innerHTML=`<div class="resetBox v643DateBox"><h3>調整旅遊日期</h3><div class="hint">請選擇這次日期變更的情境。系統會保留你已輸入的行程、住宿、預算、照片書、行李與 AI 建議。</div>${v643DateSummaryHtml()}<div class="v643DateChoices"><button class="v643DateChoice" onclick="v643ConfirmDateAdjust('range')"><b>增減天數</b><span>適合：起始日正確，只是多一天或少一天。既有日期內資料保留；超出範圍資料只暫存保留。</span></button><button class="v643DateChoice" onclick="v643ConfirmDateAdjust('shift')"><b>整趟平移</b><span>適合：整趟旅行日期錯一天或多天。行程、住宿、照片、預算日期會一起往前或往後移。</span></button></div><div class="btns"><button class="btn soft" onclick="cancelDateReset()">取消</button></div></div>`;modal.classList.add("show")}
function v643ConfirmDateAdjust(mode){const basic=v643PendingBasic;if(!basic)return cancelDateReset();const oldStart=data.trip.start;const outBefore=v643OutOfRangeCounts(basic.start,basic.end);v643ApplyBasicFields(basic);if(mode==="shift"){const offset=v643DaysBetween(oldStart,basic.start);v643ShiftTripDateData(offset)}data.trip.start=basic.start;data.trip.end=basic.end;data.days=mkDays(data.trip.start,data.trip.end);if(!data.days.some(d=>d.key===cur))cur=data.days[0]?.key||data.trip.start;if(window.currentDay&&!data.days.some(d=>d.key===currentDay))currentDay=cur;if(typeof v18SortHotels==="function")v18SortHotels();v643PendingBasic=null;v19PendingDates=null;$("dateResetModal")?.classList.remove("show");silentSave();render();if(typeof v63UpdateCurrentTripMeta==="function")setTimeout(()=>v63UpdateCurrentTripMeta(true),80);toast(mode==="shift"?"已整趟平移日期，資料已保留":outBefore.total?`已調整日期，${outBefore.total} 筆日期外資料已安全保留`:"已調整日期，資料已保留")}
function v643SaveBasicNoDateChange(basic){v643ApplyBasicFields(basic);data.trip.start=basic.start;data.trip.end=basic.end;data.days=mkDays(data.trip.start,data.trip.end);if(!data.days.some(d=>d.key===cur))cur=data.days[0]?.key||data.trip.start;if(typeof v18SortHotels==="function")v18SortHotels();silentSave();render();const d=document.querySelectorAll("#tripView details.card")[0];if(d)d.removeAttribute("open");if(typeof v63UpdateCurrentTripMeta==="function")setTimeout(()=>v63UpdateCurrentTripMeta(true),80);toast("已幫你存好囉！")}

/* v643 最終版 saveBasic（直接整合，不用 wrapper 鏈） */
function v643OutOfRangeNoticeHtml(){if(!data?.trip?.start||!data?.trip?.end)return"";const out=v643OutOfRangeCounts(data.trip.start,data.trip.end);if(!out.total)return"";return`<div class="card v643OutNotice"><h3>日期外資料已保留</h3><div class="box pink">目前有 ${out.total} 筆資料不在旅遊日期範圍內，系統沒有刪除它們。若需要恢復，可再延長日期或把旅程日期平移回來。</div></div>`}

/* ── 同步狀態工具 ── */
function renderTrip(){const h=editingHotelId?data.hotels.find(x=>x.id==editingHotelId):null;const selectedCity=typeof v15CurrentCity==="function"?v15CurrentCity():(data.trip.city||"");const mapObj=typeof v15CountryCityMaps==="function"?v15CountryCityMaps().cityMap:{};const list=mapObj[data.trip.country]||[];const customCity=list.includes(selectedCity)?"":selectedCity;const showCustom=data.trip.country==="其他"||!list.includes(selectedCity);v18SortHotels();$("tripView").innerHTML=`<div class="section"><div><h2>🌏 旅遊地設定</h2><div class="hint">儲存旅遊地後，所有功能才會解鎖。</div></div></div>
${v643OutOfRangeNoticeHtml()}
<details class="card"><summary>① 🌏 旅遊地與旅伴</summary><div class="detailBody">
  <div class="three compactMobile">
    <div><label>國家 / 區域</label><select id="country" onchange="handleCountrySelectChange()">${countryOptions()}</select></div>
    <div><label>城市 / 路線</label><select id="citySelect" onchange="updateDestByCity()">${v15CityOptions(selectedCity)}</select></div>
    <div id="customCityBox" class="full" style="display:${showCustom?"block":"none"}"><label>自訂目的地</label><input id="cityCustom" value="${esc(customCity)}" oninput="updateDestByCity()" placeholder="例：釜山＋慶州"></div>
  </div>
  <div class="two">
    <div><label>幣別</label><input id="currency" value="${esc(data.trip.currency)}" oninput="countryChanged()"></div>
    <div><label id="rateLabel">匯率：1 ${esc(data.trip.currency)} = TWD</label><input id="rateSetup" type="number" step="0.0001" value="${data.trip.rate}"></div>
  </div>
  <div class="three compactMobile">
    <div><label>出發日</label><input id="start" type="date" value="${data.trip.start}"></div>
    <div><label>回程日</label><input id="end" type="date" value="${data.trip.end}"></div>
    <div class="full"><label>匯率查詢</label><button class="btn blue compact" onclick="openRateSearch()">查一下匯率</button></div>
  </div>
  <div class="two">
    <div><label>旅遊人數</label><select id="travelerCount" onchange="previewTravelerCount()">${[1,2,3,4,5,6,7,8].map(n=>`<option value="${n}" ${Number(data.trip.travelerCount)==n?"selected":""}>${n} 人</option>`).join("")}</select></div>
    <div class="hint" style="align-self:end">目前目的地：${esc(data.trip.dest||"尚未設定")}</div>
  </div>
  <div class="grid2" id="travelerBox">${travelerInputs()}</div>
  <div class="btns"><button class="btn dark" onclick="saveBasic()">存好旅遊地設定</button></div>
</div></details>`}

/* ── renderStay（航班住宿，獨立 tab） ── */
function renderStay(){if(!$("stayView"))return;const h=editingHotelId?data.hotels.find(x=>x.id==editingHotelId):null;v18SortHotels();$("stayView").innerHTML=`<div class="section"><div><h2>✈️ 航班與住宿</h2></div></div>
<div class="stayFlightCard">
  <details class="card flightDense" id="flightCard">
    <summary>✈️ 航班設定</summary>
    <div class="detailBody">
      <div class="grid2">
        <div class="box blue"><h3>去程</h3>${flightForm("out")}</div>
        <div class="box pink"><h3>回程</h3>${flightForm("back")}</div>
      </div>
      ${flightStatusHtml()}
      <div class="btns"><button class="btn dark" onclick="saveFlights()">存好航班設定</button></div>
    </div>
  </details>
</div>
<details class="card" ${v16KeepHotelOpen||editingHotelId?"open":""}>
  <summary>🏨 住宿</summary>
  <div class="detailBody">
    <div class="three compactMobile">
      <div class="full"><label>住宿名稱</label><input id="hname" value="${esc(h?.name||"")}"></div>
      <div><label>入住日</label><input id="hstart" type="date" min="${data.trip.start}" max="${data.trip.end}" value="${h?.start||data.trip.start}"></div>
      <div><label>退房日</label><input id="hend" type="date" min="${data.trip.start}" max="${data.trip.end}" value="${h?.end||data.trip.end}"></div>
    </div>
    <label>地址</label>
    <div class="two"><input id="haddr" value="${esc(h?.addr||"")}" placeholder="可手動貼上飯店地址"><button class="btn blue compact" onclick="searchHotelAddress()">查地圖</button></div>
    <label>備註</label><textarea id="hnote">${esc(h?.note||"")}</textarea>
    <div class="btns">
      <button class="btn dark" onclick="saveHotel()">${h?"存好住宿修改":"新增住宿"}</button>
      ${h?'<button class="btn soft" onclick="editingHotelId=null;v16KeepHotelOpen=true;renderStay()">取消編輯</button>':""}
    </div>
    <div class="hotelSortedNote">住宿會依入住日自動排序；可選日期已限制在旅遊日期內。</div>
    <div class="grid2" style="margin-top:10px">${data.hotels.map(hotelCard).join("")||'<div class="empty">還沒有新增住宿</div>'}</div>
  </div>
</details>`;v16KeepHotelOpen=false;setTimeout(()=>{["out","back"].forEach(k=>toggleFlightSegments(k));const el=document.getElementById("flightCard");if(el)el.classList.add("flightDense")},0)}

/* ── renderPlanner（含 address 欄，最終版） ── */
