/* ── theme.js ── */

function getThemePrefs(){try{return JSON.parse(localStorage.getItem(THEME_STORAGE_KEY)||"{}")}catch(e){return{}}}
function applyThemePrefs(prefs=getThemePrefs()){const safe={mode:THEME_CONFIG.modes[prefs.mode]?prefs.mode:"light",palette:THEME_CONFIG.palettes[prefs.palette]?prefs.palette:"seoul",cardStyle:THEME_CONFIG.cardStyles[prefs.cardStyle]?prefs.cardStyle:"soft"};document.body.setAttribute("data-theme-mode",safe.mode);document.body.setAttribute("data-theme-palette",safe.palette);document.body.setAttribute("data-card-style",safe.cardStyle);return safe}
function setThemePrefs(partial){const current=applyThemePrefs(getThemePrefs());const next={...current,...partial};saveThemePrefs(next);applyThemePrefs(next);renderThemeWidgetState();toast("主題已套用")}
function themeOptions(obj,selected){return Object.entries(obj).map(([key,val])=>`<option value="${key}" ${key===selected?"selected":""}>${val.label}</option>`).join("")}
function renderThemeWidgetState(){const prefs=applyThemePrefs(getThemePrefs());if($("themeModeSelect"))$("themeModeSelect").value=prefs.mode;if($("themePaletteSelect"))$("themePaletteSelect").value=prefs.palette;if($("themeCardStyleSelect"))$("themeCardStyleSelect").value=prefs.cardStyle;if($("themeCurrentText"))$("themeCurrentText").textContent=v634ThemeLabel()}
function ensureThemePanel(){if(!document.body)return;if(!$("themePanelBackdrop")){const prefs=applyThemePrefs(getThemePrefs());document.body.insertAdjacentHTML("beforeend",`<div class="themePanelBackdrop noPrint" id="themePanelBackdrop" onclick="if(event.target===this)closeThemePanel()"><div class="themePanel" role="dialog" aria-modal="true" aria-labelledby="themePanelTitle"><div class="themePanelHead"><div><h3 id="themePanelTitle">🎨 外觀設定</h3><p>調整整體色系、明暗與卡片風格。這只會改畫面外觀，不會影響旅程資料。</p></div><button class="themeCloseBtn" type="button" onclick="closeThemePanel()">×</button></div><div class="themePanelControls"><div class="themeField"><label>明暗模式</label><select id="themeModeSelect" onchange="setThemePrefs({mode:this.value})">${themeOptions(THEME_CONFIG.modes,prefs.mode)}</select></div><div class="themeField"><label>色系風格</label><select id="themePaletteSelect" onchange="setThemePrefs({palette:this.value})">${themeOptions(THEME_CONFIG.palettes,prefs.palette)}</select></div><div class="themeField"><label>卡片樣式</label><select id="themeCardStyleSelect" onchange="setThemePrefs({cardStyle:this.value})">${themeOptions(THEME_CONFIG.cardStyles,prefs.cardStyle)}</select></div></div><div class="themePanelNote">外觀設定只儲存在這台裝置，不影響雲端同步與旅行資料。</div></div></div>`)}renderThemeWidgetState()}
function ensureAccountThemeButton(){const menu=$("accountMenu");if(!menu||$("menuTheme"))return;const logout=$("menuLogout");const btn=document.createElement("button");btn.id="menuTheme";btn.type="button";btn.textContent="外觀設定";btn.onclick=function(){closeAccountMenu?.();openThemePanel()};if(logout)menu.insertBefore(btn,logout);else menu.appendChild(btn)}
function openThemePanel(){ensureThemePanel();const el=$("themePanelBackdrop");if(el){renderThemeWidgetState();el.classList.add("show")}}
function closeThemePanel(){$("themePanelBackdrop")?.classList.remove("show")}
function toggleThemeWidget(){openThemePanel()}
document.addEventListener("keydown",function(e){if(e.key==="Escape")closeThemePanel()})

/* 旅程卡片色系 */
