/* ── trip.js ── */

function v634ThemeLabel(){const prefs=applyThemePrefs(getThemePrefs());const mode=THEME_CONFIG.modes[prefs.mode]?.label||"淺色";const palette=THEME_CONFIG.palettes[prefs.palette]?.label||"韓系清新";return`${palette}・${mode}`}
function v636ColorKey(v){return V636_CARD_COLORS.some(c=>c.key===v)?v:"cream"}
function v637ColorDotSet(selected="cream",id="",mode="trip"){const val=v636ColorKey(selected);return`<div class="tripColorDots" role="group" aria-label="卡片色系">${V636_CARD_COLORS.map(({key,label})=>{const active=key===val?" active":"";const onclick=mode==="new"?`v637SetNewTripColor('${key}')`:`updateTripCardColor('${id}','${key}')`;return`<button type="button" class="tripColorDot color-${key}${active}" title="${label}" aria-label="${label}" onclick="${onclick}"></button>`}).join("")}</div>`}
function v637SetNewTripColor(color){const v=v636ColorKey(color);const input=$("newTripColor");if(input)input.value=v;const box=$("newTripColorDots");if(box)box.innerHTML=v637ColorDotSet(v,"","new")}
async function updateTripCardColor(id,color){const t=tripList.find(x=>x.id===id);if(!t)return;t.cardColor=v636ColorKey(color);t.updatedAtClient=Date.now();v63SaveTripListLocal?.();renderTripList();try{await v63SaveTripListCloud?.()}catch(e){console.warn(e)}toast("已更新旅程卡片色系")}

/* ── v643 日期調整系統（直接整合版，不用 wrapper） ── */
function v649DeviceName(){const ua=navigator.userAgent||"";if(/iPad/i.test(ua)||(navigator.platform==="MacIntel"&&navigator.maxTouchPoints>1))return"iPad";if(/iPhone/i.test(ua))return"iPhone";if(/Android/i.test(ua))return/Mobile/i.test(ua)?"Android 手機":"Android 平板";if(/Mac/i.test(ua))return"Mac";if(/Windows/i.test(ua))return"Windows";return"此裝置"}
function v649Now(){return Date.now()}
function v649LockPayload(){return{deviceId:v649DeviceId,deviceName:v649DeviceName(),uid:fbUser?.uid||"",email:fbUser?.email||"",tripId:currentTripId||"",updatedAtClient:v649Now()}}
function v649IsOtherActiveLock(lock){if(!lock||!lock.deviceId)return false;if(lock.deviceId===v649DeviceId)return false;const at=Number(lock.updatedAtClient||0);return!!at&&(v649Now()-at)<V649_LOCK_TTL}
function v649LockOwnerText(lock=v649LockOwner){if(!lock)return"其他裝置";const name=lock.deviceName||"其他裝置";const time=lock.updatedAtClient?new Date(lock.updatedAtClient).toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit"}):"";return`${name}${time?"（"+time+"）":""}`}
function v649StopHeartbeat(){if(v649HeartbeatTimer){clearInterval(v649HeartbeatTimer);v649HeartbeatTimer=null}}
function v649StartHeartbeat(){v649StopHeartbeat();if(v649ReadOnly||!fbUser||!currentTripId||!fbDb)return;v649HeartbeatTimer=setInterval(async()=>{try{if(!v649ReadOnly&&fbUser&&currentTripId&&fbDb)await tripDocRef().set({editingLock:v649LockPayload(),lockUpdatedAtClient:v649Now()},{merge:true})}catch(e){console.warn("v649 lock heartbeat failed",e)}},V649_HEARTBEAT_MS)}
function v649SetReadOnly(on,lock=null){v649ReadOnly=!!on;v649LockOwner=lock||null;document.body.classList.toggle("v649-readonly",v649ReadOnly);if(v649ReadOnly){v649StopHeartbeat();setSyncStatus("warn","檢視模式",`這趟旅程目前由 ${v649LockOwnerText(lock)} 編輯`)}v649ApplyLockBanner();try{if(typeof updateAccountSyncLine==="function")updateAccountSyncLine()}catch(e){}}
function v649EnsureBanner(){const header=document.querySelector("#mainApp header")||document.querySelector(".app header");if(!header||!currentTripId)return null;let el=document.getElementById("v649LockBanner");if(!el){el=document.createElement("div");el.id="v649LockBanner";el.className="v649LockBanner noPrint v649-allow";header.appendChild(el)}return el}
function v649ApplyLockBanner(){const el=v649EnsureBanner();if(!el)return;if(!fbUser||!currentTripId){el.remove();return}if(v649ReadOnly){el.className="v649LockBanner noPrint v649-allow viewOnly";el.innerHTML=`<div><b>檢視模式：避免多裝置同步互相覆蓋</b><span>這趟旅程目前由 ${esc(v649LockOwnerText())} 編輯。此裝置可查看與載入最新雲端資料，但不會自動同步覆蓋。</span></div><div class="btns"><button class="btn blue compact v649-allow" onclick="loadFromCloud({force:true})">載入最新</button><button class="btn dark compact v649-allow" onclick="v649TakeOverEdit()">接手編輯</button></div>`}else{el.className="v649LockBanner noPrint v649-allow editing";el.innerHTML=`<div><b>目前由此裝置編輯</b><span>${esc(v649DeviceName())} 正在編輯這趟旅程。其他裝置會進入檢視模式，避免舊資料覆蓋。</span></div><div class="btns"><button class="btn blue compact v649-allow" onclick="saveToCloudNow()">同步</button><button class="btn soft compact v649-allow" onclick="loadFromCloud({force:true})">載入</button></div>`}}
async function v649AcquireEditLock({takeover=false}={}){if(!fbUser||!fbDb||!currentTripId||typeof tripDocRef!=="function"){v649SetReadOnly(false,null);return true}try{const ref=tripDocRef();const snap=await ref.get();const lock=snap.exists?(snap.data()?.editingLock||null):null;if(v649IsOtherActiveLock(lock)&&!takeover){v649SetReadOnly(true,lock);v649StartLockListener();return false}await ref.set({editingLock:v649LockPayload(),lockUpdatedAtClient:v649Now()},{merge:true});v649SetReadOnly(false,null);v649StartHeartbeat();v649StartLockListener();setSyncStatus("on","已取得編輯權",`${v649DeviceName()} 可編輯並同步`);return true}catch(e){console.warn("v649 acquire lock failed",e);v649SetReadOnly(true,{deviceName:"雲端鎖定狀態未知",updatedAtClient:v649Now()});return false}}
function v649StartLockListener(){try{if(v649LockUnsub){v649LockUnsub();v649LockUnsub=null}}catch(e){}if(!fbUser||!fbDb||!currentTripId||typeof tripDocRef!=="function")return;const tripIdAtStart=currentTripId;try{v649LockUnsub=tripDocRef().onSnapshot(snap=>{if(tripIdAtStart!==currentTripId||!snap.exists)return;const lock=snap.data()?.editingLock||null;if(v649IsOtherActiveLock(lock)){if(!v649ReadOnly||v649LockOwner?.deviceId!==lock.deviceId){v649SetReadOnly(true,lock);toast(`已切換檢視模式：${v649LockOwnerText(lock)} 正在編輯`)}}else if(lock?.deviceId===v649DeviceId&&v649ReadOnly){v649SetReadOnly(false,null);v649StartHeartbeat()}},err=>console.warn("v649 lock listener failed",err))}catch(e){console.warn(e)}}
async function v649TakeOverEdit(){if(!fbUser||!currentTripId)return toast("請先登入並選擇旅程");const ok=confirm("要改由此裝置接手編輯嗎？\n\n系統會先載入雲端最新資料，再取得編輯權，避免用舊資料覆蓋。");if(!ok)return;try{v649SetReadOnly(false,null);await loadFromCloud({force:true,silent:true,skipLock:true});await v649AcquireEditLock({takeover:true});render();toast("已接手編輯，並載入最新雲端資料")}catch(e){v649SetReadOnly(true,v649LockOwner);alert("接手編輯失敗："+(e?.message||e))}}
async function v649EnsureCanWrite(){if(!fbUser||!currentTripId)return false;if(v649ReadOnly)return false;try{const snap=await tripDocRef().get();const lock=snap.exists?(snap.data()?.editingLock||null):null;if(v649IsOtherActiveLock(lock)){v649SetReadOnly(true,lock);return false}if(!lock||lock.deviceId!==v649DeviceId||(v649Now()-Number(lock.updatedAtClient||0))>V649_LOCK_TTL)return await v649AcquireEditLock({takeover:false});return true}catch(e){console.warn("v649 ensure write failed",e);v649SetReadOnly(true,{deviceName:"雲端鎖定狀態未知",updatedAtClient:v649Now()});return false}}

/* ── 最終整合版 save / silentSave（含裝置鎖） ── */
function v63UserKey(){return(fbUser?.uid||"guest")}
function v63CloneBase(){const d=structuredClone(base);d.days=mkDays(d.trip.start,d.trip.end);return d}
function v63NormalizeData(s){let d=v63CloneBase();if(s&&typeof s==="object")Object.assign(d,s);d.meta={...base.meta,...(s?.meta||{})};d.trip={...base.trip,...(s?.trip||{})};if(!d.trip.travelers){d.trip.travelers=[d.trip.a||"A",d.trip.b||"B"];d.trip.travelerCount=d.trip.travelers.length}d.flights={out:{...base.flights.out,...(s?.flights?.out||{})},back:{...base.flights.back,...(s?.flights?.back||{})}};if(!d.days?.length&&d.trip?.start&&d.trip?.end)d.days=mkDays(d.trip.start,d.trip.end);if(!d.packing?.length)d.packing=base.packing.map(x=>({...x,id:x.id||uid()}));if(!d.expenses)d.expenses=[];if(!d.hotels)d.hotels=[];if(!d.spots)d.spots=[];if(!d.plans)d.plans=[];if(!d.conns)d.conns=[];if(!d.photos)d.photos=[];if(!d.dayCovers)d.dayCovers={};if(!d.dayCoverMeta)d.dayCoverMeta={};return d}
function v63IsAllowed(user){const email=(user?.email||"").toLowerCase();return V63_ALLOWED_EMAILS.map(x=>x.toLowerCase()).includes(email)}
function v63TripReady(){return!!(data?.trip?.country&&data?.trip?.dest&&data?.trip?.start&&data?.trip?.end&&data?.days?.length)}
function v63LoadTripListLocal(){try{return JSON.parse(localStorage.getItem(getTripListKey())||"[]").filter(Boolean)}catch(e){return[]}}
function v63SaveTripListLocal(){localStorage.setItem(getTripListKey(),JSON.stringify(tripList))}
function v63TripMetaFromData(id=currentTripId){return{id,title:data?.meta?.title||data?.trip?.dest||"未命名旅程",dest:data?.trip?.dest||"未設定",country:data?.trip?.country||"",start:data?.trip?.start||"",end:data?.trip?.end||"",updatedAtClient:Date.now(),archived:false}}
async function v63UpdateCurrentTripMeta(saveCloud=true){if(!currentTripId)return;const idx=tripList.findIndex(t=>t.id===currentTripId);const old=idx>=0?tripList[idx]:{};const meta={...old,...v63TripMetaFromData(currentTripId),archived:old.archived||false,cardColor:old.cardColor||"cream"};if(idx>=0)tripList[idx]=meta;else tripList.unshift(meta);if(saveCloud)await v63SaveTripListCloud();else v63SaveTripListLocal()}
function v63DefaultTripData({title,country,city,start,end}){const d=v63CloneBase();d.meta.title=title||"我的新旅程";d.trip.country=country||"韓國";d.trip.city=city||"釜山";d.trip.dest=v15DestinationName(d.trip.country,d.trip.city);d.trip.currency=currencyMap[d.trip.country]||"USD";d.trip.rate=rateMap[d.trip.currency]||1;d.trip.start=start||"";d.trip.end=end||"";d.days=d.trip.start&&d.trip.end?mkDays(d.trip.start,d.trip.end):[];d.flights={out:{...base.flights.out},back:{...base.flights.back}};d.hotels=[];d.expenses=[];d.spots=[];d.plans=[];d.conns=[];d.photos=[];d.dayCovers={};d.dayCoverMeta={};d.packing=base.packing.map(x=>({...x,id:uid(),checked:false}));return d}
function v63CurrentTripTitle(){const t=tripList.find(x=>x.id===currentTripId);return t?.title||data?.meta?.title||"目前旅程"}
function v63TripIndexRef(){if(!fbUser)throw new Error("尚未登入");return fbDb.collection("users").doc(fbUser.uid).collection("tripIndex").doc("list")}
function tripDocRef(){if(!fbUser)throw new Error("尚未登入");if(!currentTripId)throw new Error("尚未選擇旅程");return fbDb.collection("users").doc(fbUser.uid).collection("trips").doc(currentTripId)}
async function v63SaveTripListCloud(){v63SaveTripListLocal();if(fbUser&&fbDb)await v632SaveTripIndexCloud()}
async function loadTrips(){const localList=v63LoadTripListLocal();tripList=[...localList];if(fbUser&&fbDb){try{const snap=await v63TripIndexRef().get();const cloudList=(snap.exists&&Array.isArray(snap.data()?.trips))?snap.data().trips:[];const map=new Map();[...cloudList,...localList].forEach(t=>{if(!t?.id)return;const old=map.get(t.id);if(!old||Number(t.updatedAtClient||0)>=Number(old.updatedAtClient||0))map.set(t.id,t)});tripList=[...map.values()].sort((a,b)=>Number(b.updatedAtClient||0)-Number(a.updatedAtClient||0));v63SaveTripListLocal();if(tripList.length)await v632SaveTripIndexCloud()}catch(e){console.warn("loadTrips fallback local",e);setSyncStatus("off","旅程清單同步失敗",e.message||String(e))}}return tripList}

/* v637 title edit */
function v637EnsureEditModal(){if($("titleEditModal"))return;document.body.insertAdjacentHTML("beforeend",`<div class="titleEditModal noPrint" id="titleEditModal" role="dialog" aria-modal="true" aria-labelledby="titleEditHeading" aria-hidden="true"><div class="titleEditBox"><div class="titleEditHead"><div><span class="titleEditKicker">貞選旅管家</span><h3 id="titleEditHeading">編輯旅程標題</h3></div><button class="iconBtn" type="button" onclick="$('titleEditModal').classList.remove('show');$('titleEditModal').setAttribute('aria-hidden','true')" aria-label="關閉">×</button></div><div class="titleEditBody"><label id="titleEditLabel">旅程標題</label><textarea id="titleEditInput"></textarea><div class="hint" id="titleEditHint">修改後會儲存在目前旅程資料中，並隨同步保存。</div></div><div class="btns titleEditActions"><button class="btn soft" type="button" onclick="v637CloseTitleModal()">取消</button><button class="btn dark" type="button" onclick="v637SaveTitleModal()">儲存</button></div></div></div>`)}
let v637EditMode="title";
function v637OpenTitleModal(mode){v637EnsureEditModal();v637EditMode=mode;const isTitle=mode==="title";$("titleEditHeading").textContent=isTitle?"編輯旅程標題":"編輯旅程副標";$("titleEditLabel").textContent=isTitle?"旅程標題":"副標文字";$("titleEditInput").value=isTitle?(data.meta.title||"我的旅程"):(data.meta.subtitle||base.meta.subtitle||"");$("titleEditInput").style.minHeight=isTitle?"88px":"150px";$("titleEditModal").classList.add("show");$("titleEditModal").setAttribute("aria-hidden","false");setTimeout(()=>$("titleEditInput")?.focus(),30)}
function v637CloseTitleModal(){const m=$("titleEditModal");if(m){m.classList.remove("show");m.setAttribute("aria-hidden","true")}}
function v637SaveTitleModal(){const value=($("titleEditInput")?.value||"").trim();if(!value)return toast("請輸入內容");if(v637EditMode==="title")data.meta.title=value;else data.meta.subtitle=value;v637CloseTitleModal();save();toast("已更新旅程文字")}
function editTitle(){v637OpenTitleModal("title")}
function editSubtitle(){v637OpenTitleModal("subtitle")}

/* v637 頁尾注入 */
function v637EnsureFooter(){if(!document.body)return;if($("siteFooter"))return;const el=document.createElement("div");el.id="siteFooter";el.className="siteFooter noPrint";el.innerHTML=`<div class="siteFooterBrand">貞選旅管家 <span>Janeselect Travel Manager</span></div><div class="siteFooterVersion">${V653_VERSION_SHORT}</div><div class="siteFooterLinks"><button type="button" onclick="toast('服務條款：本工具僅供個人旅行規劃使用')">服務條款</button><span>・</span><button type="button" onclick="toast('隱私權政策：資料儲存在 Firebase 與 Cloudinary，不做其他用途')">隱私權政策</button></div>`;document.body.appendChild(el)}

/* ── 帳號 Widget（v635 版，直接整合外觀設定按鈕） ── */
function initialsFromUser(user){const name=user?.displayName||user?.email||"登入";if(!user)return"登入";const parts=name.split(/\s+/).filter(Boolean);if(parts.length>=2)return(parts[0][0]+parts[1][0]).toUpperCase();return name.slice(0,2).toUpperCase()}
function renderAccountWidget(user){const logged=!!user,avatar=$("accountAvatar"),label=$("accountLabel"),name=$("accountName"),email=$("accountEmail");if(!avatar)return;if(logged){if(user.photoURL)avatar.innerHTML=`<img src="${user.photoURL}" alt="avatar">`;else avatar.textContent=initialsFromUser(user);if(label)label.textContent="已登入";if(name)name.textContent=user.displayName||"Google 帳號";if(email)email.textContent=user.email||""}else{avatar.textContent="登入";if(label)label.textContent="Google 登入";if(name)name.textContent="尚未登入";if(email)email.textContent="登入後可跨裝置同步"};["menuLoad","menuSave","menuLogout"].forEach(id=>{if($(id))$(id).style.display=logged?"block":"none"});if($("menuLogin"))$("menuLogin").style.display=logged?"none":"block";ensureAccountThemeButton()}
function toggleAccountMenu(){ensureAccountThemeButton();$("accountMenu")?.classList.toggle("show")}
function closeAccountMenu(){$("accountMenu")?.classList.remove("show")}
document.addEventListener("click",function(e){const w=$("accountWidget");if(w&&!w.contains(e.target))closeAccountMenu()})

/* ── 帳號同步狀態 ── */
function ensureAccountMenuSyncLine(){const menu=$("accountMenu");if(menu&&!$("accountSyncLine")){const who=menu.querySelector(".who");if(who)who.insertAdjacentHTML("afterend",`<div class="accountSyncLine" id="accountSyncLine"><span class="dot"></span>尚未同步</div>`)}updateAccountSyncLine()}

/* ── v63 顯示控制 ── */
function v63ShowShell(mode){const login=$("loginView"),list=$("tripListView"),app=$("mainApp")||document.querySelector(".app");if(login)login.classList.toggle("hidden",mode!=="login");if(list)list.classList.toggle("hidden",mode!=="list");if(app)app.classList.toggle("hidden",mode!=="app");if($("accountWidget"))$("accountWidget").style.display=mode==="app"?"":"none"}
function renderLoginView(message=""){const el=$("loginView");if(!el)return;const signed=!!fbUser;el.innerHTML=`<div class="gateShell"><div class="loginCard"><div class="loginBrand"><span class="brandMark" aria-hidden="true"><svg viewBox="0 0 64 64" focusable="false"><rect x="10" y="13" width="40" height="43" rx="10"></rect><path d="M22 13c1.7-5.4 13.9-5.4 15.6 0"></path><path d="M21 28h18M21 38h14"></path><circle cx="45" cy="18" r="6"></circle><path d="M45 14v4l3 2"></path></svg></span><span><b>貞選旅管家</b><small>Janeselect Travel Manager</small></span></div><h1>Janeselect Travel Manager</h1><p>登入後才能建立與管理旅程。現階段採 Email 白名單開放，每個帳號最多可建立 ${V63_MAX_TRIPS} 個旅程。</p>${message?`<div class="box pink" style="margin-top:12px">${esc(message)}</div>`:""}<div class="btns"><button class="btn dark" onclick="firebaseSignIn()">使用 Google 登入</button>${signed?'<button class="btn soft" onclick="firebaseSignOut()">登出目前帳號</button>':""}</div><div class="cloudHint">目前白名單：${V63_ALLOWED_EMAILS.map(esc).join("、")}</div></div></div>`}

/* ── v637 最終版 renderTripList（直接整合，不用 wrapper 鏈） ── */
function renderTripList(){const el=$("tripListView");if(!el)return;const active=tripList.filter(t=>!t.archived);const archived=tripList.filter(t=>t.archived);el.innerHTML=`<div class="gateShell"><div class="tripListHero"><div><div class="loginBrand"><span class="brandMark" aria-hidden="true"><svg viewBox="0 0 64 64" focusable="false"><rect x="10" y="13" width="40" height="43" rx="10"></rect><path d="M22 13c1.7-5.4 13.9-5.4 15.6 0"></path><path d="M21 28h18M21 38h14"></path><circle cx="45" cy="18" r="6"></circle><path d="M45 14v4l3 2"></path></svg></span><span><b>貞選旅管家</b></span></div><h1>我的旅程</h1><p>每趟旅程都是一包獨立資料：旅遊地、航班住宿、行程、口袋景點、預算、行李與旅遊書都會分開保存。</p></div><div class="tripListCount">${active.length}/${V63_MAX_TRIPS} 個旅程</div></div><div class="tripGrid">${active.map(v63TripCard).join("")||'<div class="tripListCard tripColor-cream"><div class="tripCardTop"><div><span class="tripBadge">尚未開始</span><h3>還沒有旅程</h3></div></div><div class="meta">先在下方新增第一趟旅程。</div></div>'}</div>${archived.length?`<details class="tripCreateCard"><summary style="cursor:pointer;font-weight:950">封存旅程</summary><div class="tripGrid">${archived.map(v63TripCard).join("")}</div></details>`:""}<div class="tripCreateCard"><h3>＋ 新增旅程</h3><div class="tripCreateGrid"><div><label>旅程名稱</label><input id="newTripTitle" placeholder="例：2026 釜山自由行"></div><div><label>國家 / 區域</label><select id="newTripCountry" onchange="v63NewTripCountryChanged()">${Object.keys(currencyMap).map(c=>`<option value="${c}">${c}</option>`).join("")}<option value="其他">其他</option></select></div><div><label>城市 / 路線</label><input id="newTripCity" value="釜山"></div><div><label>卡片色系</label><input id="newTripColor" type="hidden" value="cream"><div id="newTripColorDots" class="newTripColorDots">${v637ColorDotSet("cream","","new")}</div></div><div><label>出發日</label><input id="newTripStart" type="date"></div><div><label>回程日</label><input id="newTripEnd" type="date"></div><div style="align-self:end"><button class="btn dark" style="width:100%" onclick="createTrip()">建立旅程</button></div></div><div class="cloudHint">建立後會先進入旅遊地設定；完成旅遊地後才會解鎖其他功能。旅程卡片色系只影響清單外觀，不會改變旅行資料。</div></div><div class="btns"><button class="btn soft" onclick="firebaseSignOut()">登出</button></div></div>`;v637EnsureFooter()}

/* v637 最終版 v63TripCard */
function v63TripCard(t){const dateText=t.start&&t.end?`${esc(short(t.start))} - ${esc(short(t.end))}`:"尚未完成";const destText=t.dest||"未設定目的地";const color=v636ColorKey(t.cardColor);return`<div class="tripListCard tripColor-${color} ${t.archived?"archived":""}"><div class="tripCardTop"><div><span class="tripBadge">${t.archived?"已封存":"旅程"}</span><h3>${esc(t.title||"未命名旅程")}</h3></div></div><div class="tripCardMetaGrid"><div><span>目的地</span><b>${esc(destText)}</b></div><div><span>日期</span><b>${dateText}</b></div></div><div class="meta">${t.updatedAtClient?`最後更新：${new Date(t.updatedAtClient).toLocaleDateString("zh-TW")}`:"尚未同步更新時間"}</div><div class="tripCardTools"><div class="tripColorControl"><span>卡片色系</span>${v637ColorDotSet(color,t.id,"trip")}</div></div><div class="btns"><button class="btn dark compact" onclick="selectTrip('${t.id}')">繼續編輯</button>${t.archived?`<button class="btn blue compact" onclick="restoreTrip('${t.id}')">還原</button>`:`<button class="btn soft compact" onclick="archiveTrip('${t.id}')">封存</button>`}<button class="btn danger compact" onclick="deleteTrip('${t.id}')">刪除</button></div></div>`}
function v63NewTripCountryChanged(){const c=$("newTripCountry")?.value;const map=v15CountryCityMaps().cityMap;const first=(map[c]||[])[0]||"";if($("newTripCity"))$("newTripCity").value=first}

/* v649 最終版 selectTrip（整合裝置鎖） */
async function selectTrip(id){v649SelectingTrip=true;try{currentTripId=id;localStorage.setItem(V63_CURRENT_TRIP_KEY,id);cloudReady=false;if(cloudUnsub){cloudUnsub();cloudUnsub=null}let localData=null,localMeta=v632GetLocalMeta(id),cloudDoc=null;try{const raw=localStorage.getItem(getLocalTripKey(id));if(raw)localData=v63NormalizeData(JSON.parse(raw))}catch(e){console.warn(e)}if(fbUser&&fbDb){try{const snap=await tripDocRef().get();if(snap.exists&&snap.data()?.data)cloudDoc=snap.data()}catch(e){console.warn(e);setSyncStatus("off","雲端讀取失敗",e.message||String(e))}}const cloudUpdated=Number(cloudDoc?.updatedAtClient||0),localUpdated=Number(localMeta?.updatedAtClient||0);suppressCloudSave=true;if(cloudDoc?.data&&cloudUpdated>=localUpdated){data=v63NormalizeData(cloudDoc.data);lastCloudUpdatedAt=cloudUpdated;setSyncStatus("on","已載入雲端資料",`旅程：${cloudDoc.tripMeta?.title||v63CurrentTripTitle()}`)}else if(localData){data=localData;if(cloudDoc?.data)setSyncStatus("warn","本機資料較新","即將補同步到雲端");else setSyncStatus("warn","雲端尚無此旅程","即將建立雲端資料")}else if(cloudDoc?.data){data=v63NormalizeData(cloudDoc.data);lastCloudUpdatedAt=cloudUpdated}else{data=v63CloneBase();setSyncStatus("off","尚無旅程資料","請先設定旅遊地")}cur=data.days?.[0]?.key||data.trip?.start||cur;currentDay=cur;v63PersistTripLocal();suppressCloudSave=false;cloudReady=!!(fbUser&&currentTripId&&v632IsAllowed());if(cloudReady)listenCloudChanges();v63ShowShell("app");view="trip";renderNav();render();scrollTo(0,0);if(cloudReady&&(!cloudDoc?.data||localUpdated>cloudUpdated+1000))scheduleCloudSave("selectTrip-local-newer");v649SelectingTrip=false;await v649AcquireEditLock({takeover:false});v649ApplyLockBanner()}catch(e){v649SelectingTrip=false;throw e}}

/* v649 最終版 createTrip（整合裝置鎖） */
async function createTrip(){const active=tripList.filter(t=>!t.archived);if(active.length>=V63_MAX_TRIPS)return toast(`每個帳號最多只能建立 ${V63_MAX_TRIPS} 個旅程`);const title=$("newTripTitle")?.value.trim()||"我的新旅程";const country=$("newTripCountry")?.value||"韓國";const city=$("newTripCity")?.value.trim()||"";const start=$("newTripStart")?.value||"";const end=$("newTripEnd")?.value||"";const cardColor=v636ColorKey($("newTripColor")?.value||"cream");if(!start||!end)return toast("請先選擇出發日與回程日");if(start>end)return toast("回程日不可早於出發日");const id=`trip_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;currentTripId=id;localStorage.setItem(V63_CURRENT_TRIP_KEY,id);data=v63DefaultTripData({title,country,city,start,end});cur=data.days?.[0]?.key||data.trip.start;currentDay=cur;tripList.unshift({...v63TripMetaFromData(id),cardColor});v63PersistTripLocal();cloudReady=!!(fbUser&&currentTripId&&v632IsAllowed());try{await v63SaveTripListCloud();if(cloudReady)await saveToCloudNow({silent:true,reason:"createTrip"})}catch(e){setSyncStatus("off","建立雲端旅程失敗",e.message||String(e))}if(cloudReady)listenCloudChanges();v63ShowShell("app");view="trip";renderNav();render();scrollTo(0,0);toast("已建立旅程");if(currentTripId)await v649AcquireEditLock({takeover:true});v649ApplyLockBanner()}
async function archiveTrip(id){if(!confirm("確定要封存這趟旅程？資料不會刪除，可在封存旅程中還原。"))return;const t=tripList.find(x=>x.id===id);if(t)t.archived=true;if(currentTripId===id){currentTripId="";localStorage.removeItem(V63_CURRENT_TRIP_KEY)}await v63SaveTripListCloud();renderTripList()}
async function restoreTrip(id){const t=tripList.find(x=>x.id===id);if(t)t.archived=false;await v63SaveTripListCloud();renderTripList()}
async function deleteTrip(id){const t=tripList.find(x=>x.id===id);if(!t)return;const title=t.title||"這趟旅程";const ok=confirm(`確定要刪除「${title}」嗎？\n\n刪除後會從旅程清單移除，並嘗試刪除雲端旅程資料。這個動作不能從網頁內復原。`);if(!ok)return;try{if(fbUser&&fbDb)await fbDb.collection("users").doc(fbUser.uid).collection("trips").doc(id).delete().catch(e=>{console.warn("delete trip cloud failed",e)})}catch(e){}tripList=tripList.filter(x=>x.id!==id);try{localStorage.removeItem(getLocalTripKey(id))}catch(e){}if(currentTripId===id){currentTripId="";localStorage.removeItem(V63_CURRENT_TRIP_KEY)}await v63SaveTripListCloud();renderTripList();toast("已刪除旅程")}

/* v649 wrap v63BackToTripList */
function v63BackToTripList(){v649StopHeartbeat();if(v649LockUnsub){try{v649LockUnsub()}catch(e){}v649LockUnsub=null}v649SetReadOnly(false,null);v63UpdateCurrentTripMeta(true);currentTripId="";localStorage.removeItem(V63_CURRENT_TRIP_KEY);renderTripList();v63ShowShell("list")}

/* v63 auth handler */
async function v63HandleAuth(user){fbUser=user||null;v63AuthPassed=!!(user&&v63IsAllowed(user));if(cloudUnsub){cloudUnsub();cloudUnsub=null}if(!user){currentTripId="";cloudReady=false;renderLoginView();v63ShowShell("login");renderAccountWidget?.(null);setSyncStatus("off","尚未登入","登入 Google 後可跨裝置同步");return}if(!v63AuthPassed){currentTripId="";cloudReady=false;renderLoginView(`${user.email||"這個帳號"} 尚未在白名單中，請改用授權帳號登入。`);v63ShowShell("login");renderAccountWidget?.(user);setSyncStatus("off","帳號未授權",user.email||"");return}setSyncStatus("warn","登入成功","載入旅程清單中");await loadTrips();renderAccountWidget?.(user);const savedId=localStorage.getItem(V63_CURRENT_TRIP_KEY)||currentTripId;if(savedId&&tripList.some(t=>t.id===savedId&&!t.archived)){await selectTrip(savedId)}else{currentTripId="";localStorage.removeItem(V63_CURRENT_TRIP_KEY);cloudReady=false;renderTripList();v63ShowShell("list");setSyncStatus("on","已載入旅程清單",`${tripList.filter(t=>!t.archived).length} 個旅程`)}}

/* ── v63RenderTripSwitchBar（v632 版含狀態徽章） ── */
function v63RenderTripSwitchBar(){const header=document.querySelector("#mainApp header")||document.querySelector(".app header");if(!header||!currentTripId)return;let bar=$("tripSwitchBar");if(!bar){bar=document.createElement("div");bar.id="tripSwitchBar";bar.className="tripSwitchBar noPrint";header.appendChild(bar)}bar.innerHTML=`<div class="miniTrip"><b>${esc(v63CurrentTripTitle())}</b><br>${esc(data.trip.dest||"未設定目的地")}｜${data.trip.start&&data.trip.end?`${esc(short(data.trip.start))}-${esc(short(data.trip.end))}`:"尚未完成日期"}<br>${v632StatusBadge()}</div><div class="btns" style="margin:0"><button class="btn soft compact" onclick="v63BackToTripList()">切換</button><button class="btn blue compact" onclick="loadFromCloud({force:true})">載入</button><button class="btn dark compact" onclick="saveToCloudNow()">同步</button></div>`}

/* ── renderHead（最終整合版） ── */
